export const COMPARE = {
  COMPARE_STATE: 'compare:state',
  COMPARE_CHANGED: 'compare:changed',
  COMPARE_ENABLED: 'compare:enabled',
  COMPARE_OFFER_SHOW: 'compare:offer-show',
  COMPARE_OFFER_CLOSE: 'compare:offer-close',
  COMPARE_OFFER_HEIGHT: 'compare:offer-height',
  COMPARE_START: 'compare:start',
  COMPARE_REFRESH: 'compare:refresh',
  COMPARE_SOURCE: 'compare:source',
  COMPARE_ARCHIVE: 'compare:archive',
  COMPARE_ARCHIVE_CHANGED: 'compare:archive-changed',
  COMPARE_ARCHIVE_OPEN: 'compare:archive-open',
  COMPARE_ARCHIVE_REMOVE: 'compare:archive-remove',
} as const;
