// Справка: длинные описания в колонке с maxWidth, поэтому английский может быть чуть длиннее.
export const HELP: Record<string, string> = {
  'локально': 'local',
  'наружу': 'cloud',
  'Вкладки, группы и окна': 'Tabs, groups and windows',
  'Вкладки стоят слева списком: у длинного заголовка есть место, а у двадцати вкладок — читаемость. Разложенное переживает перезапуск.': 'Tabs sit in a list on the left: long titles have room, and twenty tabs stay readable. The layout survives a restart.',
  'Вертикальные вкладки': 'Vertical tabs',
  'Список с перетаскиванием: вкладку можно бросить в группу, к другой вкладке — в пару, или увести в отдельное окно.': 'A draggable list: drop a tab into a group, onto another tab to split, or into its own window.',
  'Группы': 'Groups',
  'Своё имя и цвет, сворачивание одним кликом, вложенность. Пустая группа убирается сама, чтобы список не зарастал.': 'Own name and color, one-click collapse, nesting. An empty group removes itself so the list does not fill with husks.',
  'ПКМ по вкладке': 'Right-click a tab',
  'Закреплённые вкладки': 'Pinned tabs',
  'Уезжают наверх списка узкой полосой, не закрываются случайно и восстанавливаются первыми при запуске.': 'Move to a narrow strip at the top, do not close by accident, and restore first on launch.',
  'ПКМ → Закрепить': 'Right-click → Pin',
  'Split — две страницы рядом': 'Split — two pages side by side',
  'Доля тянется разделителем; половины меняются местами, если перетащить панель за её шапку на соседнюю. Увели в сайдбар — пара распалась, обе вкладки остались.': 'Drag the divider to resize. Drag a pane by its header onto the other to swap. Move one to the sidebar and the pair splits; both tabs stay.',
  'Перетаскивание': 'Drag and drop',
  'Перенос живой вкладки в другое окно': 'Move a live tab to another window',
  'Страница уезжает вместе с историей «назад», позицией прокрутки и уже набранным в форме текстом — это переезд, а не переоткрытие по адресу.': 'The page moves with back-history, scroll position and form text — a move, not a reopen by URL.',
  'Усыпление фоновых вкладок': 'Sleeping background tabs',
  'Давно не открытая вкладка отдаёт память системе и просыпается при клике. Выгрузка включается, только когда браузер вышел за свой бюджет и системе действительно тесно.': 'A tab you have not opened in a while gives memory back and wakes on click. Sleep starts only when the browser is over budget and the system is actually tight.',
  'Настройки → Браузер': 'Settings → Browser',
  'Инкогнито': 'Private tabs',
  'Приватная вкладка живёт в сессии в памяти: ни истории, ни автосохранения, ни следа в профиле. Адблок и VPN при этом работают.': 'A private tab lives in memory: no history, no session save, no trace in the profile. Ad blocking and VPN still work.',
  'Автосохранение сессии': 'Session autosave',
  'Вкладки, группы, сплит-пары, закреп и порядок списка пишутся на диск при закрытии окна и возвращаются целиком при следующем запуске.': 'Tabs, groups, splits, pins and order are written on close and come back whole on the next launch.',
  'Само': 'Automatic',
  'Снимок вкладки': 'Tab screenshot',
  'Снимает страницу целиком и показывает карточкой: сохранить файлом или скопировать в буфер, не уходя со страницы.': 'Captures the whole page and shows a card: save as a file or copy, without leaving the page.',
  'Буфер скопированного': 'Clipboard history',
  'История того, что вы копировали в браузере: последние записи, вытеснение старых, вставка в один клик.': 'What you copied in the browser: recent items, older ones drop off, paste in one click.',
  'Страницы ошибок по-человечески': 'Human error pages',
  'Вместо кода Chromium — что именно не получилось и что делать: сайт не отвечает, нет сети, сертификат просрочен, DNS не нашёл имя.': 'Instead of a Chromium code — what failed and what to do: the site is down, there is no network, the certificate expired, DNS found no name.',
  'Вместо ошибки': 'In place of the error',

  'Адрес и поиск': 'Address and search',
  'Одна строка на адреса и запросы — и три отдельных поиска рядом: по странице, по своим данным и по настройкам.': 'One field for addresses and queries, plus three searches beside it: on the page, in your data, and in settings.',
  'Омнибокс с подсказками': 'Omnibox with suggestions',
  'Адрес, запрос и подсказки из истории и закладок в одной строке.': 'Address, query and suggestions from history and bookmarks in one field.',
  'Бэнги': 'Bangs',
  'Запрос с восклицательным знаком уходит сразу на нужный сайт: «!yt котики», «!w Электрон». Список свой и правится.': 'A query with an exclamation mark goes straight to a site: “!yt cats”, “!w Electron”. The list is yours to edit.',
  'Быстрый поиск': 'Quick search',
  'Поповер поверх страницы с полосой целей: набрали запрос и выбрали, куда он уйдёт.': 'A panel over the page with a row of targets: type a query and pick where it goes.',
  'Поиск по странице': 'Find on page',
  'Панель со счётчиком совпадений и переходом по ним, без потери фокуса на странице.': 'A bar with a hit count and next/previous, without losing focus on the page.',
  'Смысловой поиск по странице': 'Meaning search on the page',
  'Спрашиваете словами — модель выбирает нужный фрагмент из тех, что нашли мы, и подсвечивает его прямо на странице.': 'Ask in words — the model picks a passage from what we found and highlights it on the page.',
  'Поиск по настройкам': 'Settings search',
  'Ищет теми словами, которыми вы спрашиваете: «вкладки перезагружаются» приводит к выгрузке из памяти. Работает мгновенно и без модели.': 'Matches the words you actually type: “tabs keep reloading” leads to sleeping tabs. Instant, no model required.',
  'Строка вверху настроек': 'Search field at the top of Settings',

  'Новая вкладка — рабочий стол': 'New tab — desktop',
  'Не стена ссылок, а свой экран: плитки раскладываются свободно, а один виджет можно назначить героем — он получает цвет в полную силу.': 'Not a wall of links: tiles sit freely, and one widget can be the hero with full color.',
  'Свободная раскладка плиток': 'Free tile layout',
  'Виджеты перетаскиваются и меняют размер, координаты сохраняются. Ничего не перескакивает само при добавлении новой плитки.': 'Widgets drag and resize; positions are saved. Nothing jumps when you add a tile.',
  'Правка на столе': 'Edit the desktop',
  'Виджеты': 'Widgets',
  'Часы с несколькими циферблатами, погода, курсы ЦБ, крипта, быстрые ссылки, итоги дня, плеер, календарь, отслеживание, карточки слов (язык — в настройке экрана).': 'Clock faces, weather, CB rates, crypto, shortcuts, daily digest, player, calendar, price tracking, word cards (language is in the screen settings).',
  'Настроить экран → Виджеты': 'Customize screen → Widgets',
  'Свой виджет по описанию': 'Custom widget from a description',
  'Опишите словами, что хотите видеть, — модель возвращает тип и данные по строгой грамматике, а рисует их обычный код.': 'Describe what you want — the model returns type and data in a strict grammar, and ordinary code draws it.',
  'Фон и обои': 'Background and wallpaper',
  'Обои из набора или свои, плюс правило одного героя: цвет в полную силу получает ровно одна плитка на экран.': 'Preset or custom wallpaper, plus the one-hero rule: only one tile on the screen gets full color.',
  'Настроить экран → Фон': 'Customize screen → Background',

  'Приложения на панели': 'Apps in the panel',
  'Мелкие инструменты, ради которых обычно открывают вкладку и уходят на сайт с рекламой. Здесь они живут сбоку и считают локально.': 'Small tools that usually mean opening a tab and an ads-filled site. Here they live on the side and compute locally.',
  'Калькулятор': 'Calculator',
  'Арифметика, проценты и разбор вставленной строки: скопировали «1200 + 15%» — получили ответ, не перенабирая.': 'Arithmetic, percents and pasted lines: copy “1200 + 15%” and get the answer without retyping.',
  'Панель приложений': 'Apps panel',
  'Конвертер и пояса': 'Converter and time zones',
  'Величины и валюты по свежему курсу; часовые пояса — вычислением из системной базы, без похода в сеть.': 'Units and currencies at a fresh rate; time zones from the system database, with no network trip.',
  'Таймер и счётчик': 'Timer and counter',
  'Таймер тикает в главном процессе и не сбивается, когда вкладку усыпили. Счётчик считает знаки, слова и строки.': 'The timer ticks in the main process and keeps time if the tab sleeps. The counter counts characters, words and lines.',
  'Пипетка и котёнок': 'Eyedropper and kitten',
  'Пипетка берёт цвет с экрана и отдаёт в нужном формате. Котёнок — маленький тамагочи, основа будущего маскота.': 'The eyedropper picks a screen color in the format you need. The kitten is a tiny tamagotchi — the start of a mascot.',
  'Веб-приложения': 'Web apps',
  'Любой сайт можно поставить в панель как приложение — он открывается сбоку целиком, со своим логином.': 'Any site can sit in the panel as an app — it opens on the side, with its own login.',
  'Настроить экран → Приложения': 'Customize screen → Apps',

  'Щит: блокировка и VPN': 'Shield: blocking and VPN',
  'Обе защиты живут под одним значком щита в адресной строке — там же видно, что именно сработало на этом сайте.': 'Both protections live under one shield in the address bar — that is also where you see what fired on this site.',
  'Блокировка рекламы и трекеров': 'Ad and tracker blocking',
  'Движок Ghostery со списками, которые обновляются в фоне. Отключается на отдельном сайте одним переключателем.': 'Ghostery engine with lists that update in the background. Turn it off for one site with a single switch.',
  'Щит в адресной строке': 'Shield in the address bar',
  'VPN на Xray-core': 'VPN on Xray-core',
  'Импорт подписки vless/trojan, выбор сервера со списком стран и флагами, свой процесс отдельно от браузера.': 'Import a vless/trojan subscription, pick a server from a flagged country list, run a process separate from the browser.',
  'Настройки → VPN': 'Settings → VPN',
  'Если туннель упал, трафик не идёт мимо него, а останавливается. Реальный адрес не утекает в момент обрыва.': 'If the tunnel drops, traffic stops instead of going around it. Your real address does not leak at the break.',

  'Пароли, адреса и карты': 'Passwords, addresses and cards',
  'Секреты шифруются ключом из системного хранилища и открытым текстом на диск не пишутся — ни в файлах, ни в логах.': 'Secrets are encrypted with a key from the system store and never written in plaintext — not in files, not in logs.',
  'Менеджер паролей': 'Password manager',
  'Хранилище на AES-256-GCM. Автозаполнение срабатывает без лишних кликов, индикатор в адресной строке показывает, что пароль для сайта есть.': 'AES-256-GCM vault. Autofill runs without extra clicks; an address-bar mark shows a password exists for the site.',
  'Настройки → Пароли': 'Settings → Passwords',
  'Генератор паролей': 'Password generator',
  'Появляется прямо в поле регистрации и сохраняет пароль сразу, не заставляя вспоминать, что вы придумали.': 'Appears in the signup field and saves the password at once, so you do not have to remember what you invented.',
  'В поле формы': 'In the form field',
  'Показ пароля — через Windows Hello': 'Show password — via Windows Hello',
  'Увидеть сохранённый пароль или номер карты можно только после подтверждения личности системой.': 'A saved password or card number is shown only after the system confirms it is you.',
  'Адреса и банковские карты': 'Addresses and payment cards',
  'Подставляются по подписям полей. Номер карты выдаётся под Windows Hello, CVC не хранится вовсе.': 'Filled from field labels. The card number needs Windows Hello; CVC is not stored at all.',
  'Настройки → Автозаполнение': 'Settings → Autofill',
  'Разрешения сайтов': 'Site permissions',
  'Камера, микрофон, геопозиция, уведомления — по сайту отдельно и с тремя состояниями: разрешено, запрещено и «забыть», чтобы ошибочное «нет» можно было отменить.': 'Camera, mic, location, notifications — per site, with allow, deny and forget, so a mistaken no can be undone.',
  'Настройки → Разрешения': 'Settings → Permissions',

  'Библиотека': 'Library',
  'История, закладки, загрузки, отслеживание и журнал агентов — один остров с общей строкой поиска наверху.': 'History, bookmarks, downloads, tracking and the agent log — one island with a shared search field on top.',
  'История с полнотекстовым поиском': 'History with full-text search',
  'База с индексом по текстам страниц; находки переранжирует локальная модель, поэтому «та статья про батарейки» находится и без этого слова в заголовке.': 'A database indexed on page text; a local model re-ranks hits, so “that article about batteries” is found even if the title never says so.',
  'Звезда в адресной строке, папки, перетаскивание, отдельная полка в сайдбаре.': 'Star in the address bar, folders, drag-and-drop, a shelf in the sidebar.',
  'Раскладка по ярусам «сегодня / раньше», метка происхождения файла из интернета и безопасное имя файла без сюрпризов с путями.': 'Rows for today / earlier, a mark that the file came from the internet, and a safe file name with no path tricks.',
  'Библиотека → Загрузки': 'Library → Downloads',
  'Отслеживание цен': 'Price tracking',
  'Один товар — одна карточка, даже если он найден в нескольких магазинах. Показываются факты из собственных наблюдений, а не советы, когда покупать.': 'One product, one card, even across shops. Facts from your own observations, not advice on when to buy.',
  'Библиотека → Отслеживание': 'Library → Tracking',
  '«Куда я это дел»': '“Where did I put that”',
  'Один вопрос сразу по истории, закладкам и загрузкам — когда не помнишь, была это статья, закладка или скачанный файл.': 'One question across history, bookmarks and downloads — when you cannot remember whether it was an article, a bookmark or a file.',
  'Переезд из другого браузера': 'Move from another browser',
  'Закладки, история и пароли из Chrome, Edge, Brave, Opera, Vivaldi и Яндекс.Браузера. Из свежего Chrome пароли переносятся экспортом CSV.': 'Bookmarks, history and passwords from Chrome, Edge, Brave, Opera, Vivaldi and Yandex Browser. Fresh Chrome passwords come in via CSV export.',

  'Локальные функции модели': 'Local model features',
  'Восемь функций, отобранных по жёсткому правилу: короткий вход, короткий выход, ответ проверяемой формы, один шаг и дешёвая, видимая ошибка. Ни одна не отправляет наружу ни байта.': 'Eight features picked by a hard rule: short in, short out, a checkable shape, one step, a cheap visible miss. None send a byte outside.',
  'Правка своего текста в поле ввода': 'Edit your text in a field',
  'Выделили черновик в форме — модель поправит формулировку прямо в поле. Отмена обычным Ctrl+Z работает как всегда.': 'Select a draft in a form — the model rewrites it in place. Ordinary Ctrl+Z still undoes it.',
  'Поиск вкладки по смыслу': 'Find a tab by meaning',
  '«Там, где про доставку» — модель выбирает номер вкладки из списка, который собрали мы, а не придумывает ответ словами.': '“The one about delivery” — the model picks a tab number from the list we built, instead of inventing an answer.',
  '«Навести порядок» — группировка вкладок': '“Organize tabs” — grouping',
  'Двадцать открытых вкладок раскладываются по темам одной кнопкой. Это предложение: не понравилось — откат одним движением.': 'Twenty open tabs sorted by topic with one button. It is a suggestion: one motion undoes it.',
  'Распознавание полей формы': 'Form field recognition',
  'Когда сайт назвал поля как попало, модель читает подписи рядом с ними и понимает, где имя, где адрес, где индекс.': 'When a site named fields poorly, the model reads nearby labels and sees which is name, address, postal code.',
  '«Чем занимался» — итоги дня': '“What I did” — daily digest',
  'Короткая сводка по вашей же истории: над чем шла работа, что читалось, куда ушло время.': 'A short summary of your own history: what you worked on, what you read, where the time went.',
  '«Вы это уже читали»': '“You have already read this”',
  'Подсказка, что страница уже попадалась вам раньше, и что на ней с тех пор изменилось.': 'A hint that you have seen the page before, and what changed since then.',
  'Смысловой Ctrl+F': 'Meaning Ctrl+F',
  'Тот же поиск по странице, но вопросом. Модель показывает место на странице, а не пересказывает его своими словами.': 'The same find-on-page, asked as a question. The model shows the place; it does not retell it.',
  'Фраза → правило': 'Phrase → rule',
  '«Ссылки с habr.com открывай в группе Чтение» превращается в правило — но сначала показывается карточкой подтверждения.': '“Open habr.com links in the Reading group” becomes a rule — after a confirmation card.',

  'Блокнот и граф': 'Notebook and graph',
  'Два больших экрана для работы с материалом. Маленькая локальная модель не планирует на длинном горизонте — поэтому план рисует человек, а модель делает один узкий шаг.': 'Two large screens for working with material. A small local model does not plan far ahead — you draw the plan, the model takes one narrow step.',
  'Блокнот с источниками': 'Notebook with sources',
  'Несколько независимых блокнотов; источники — ссылки и локальные файлы (pdf, docx, txt, md, csv). Чат заземлён на них и отвечает по вашим материалам.': 'Several independent notebooks; sources are links and local files (pdf, docx, txt, md, csv). Chat is grounded on them and answers from your material.',
  'Большой AI-экран': 'Large AI screen',
  'Студия: пять форматов': 'Studio: five formats',
  'Саммари, майндкарта, инфографика, интерактивный тест и статья-страница в трёх стилях — её можно открыть вкладкой или сохранить одним файлом .html.': 'Summary, mind map, infographic, interactive quiz and an article page in three styles — open as a tab or save as one .html file.',
  'Блокнот → Студия': 'Notebook → Studio',
  'Граф-воркспейс': 'Graph workspace',
  'Холст, где вы сами рисуете план связями. Узлы: страница, заметка, шаг модели, результат, артефакты Студии, веб-поиск и фактчек.': 'A canvas where you draw the plan with links. Nodes: page, note, model step, result, Studio artifacts, web search and fact-check.',
  'Чужой ИИ-сайт как узел': 'Someone else’s AI site as a node',
  'ChatGPT или Claude открываются в панели один в один. Кнопку «отправить» жмёте вы — код не автоматизирует чужой интерфейс никогда.': 'ChatGPT or Claude open in the panel as they are. You press send — the code never automates someone else’s UI.',
  'Граф → узел': 'Graph → node',

  'Хаб и облачные части': 'Hub and cloud parts',
  'Облачное в браузере есть, и оно названо прямо. Эти службы не получают ни вкладок, ни истории, ни черновиков — только тот запрос, который вы набрали сами.': 'Cloud features exist and are named as such. They get neither tabs, nor history, nor drafts — only the query you typed.',
  'AI-хаб на новой вкладке': 'AI hub on the new tab',
  'Свой чат прямо на стартовом экране, с историей разговоров и переключением модели.': 'A chat on the start screen, with conversation history and a model switch.',
  'Веб-поиск и фактчек': 'Web search and fact-check',
  'Ответ можно подкрепить свежей выдачей (SearXNG) или проверить фактчеком (Gemini). И то и другое — по вашему явному действию, а не в фоне.': 'Back an answer with fresh results (SearXNG) or a fact-check (Gemini). Both happen on your explicit action, not in the background.',
  'Облачные модели по своему ключу': 'Cloud models with your own key',
  'Ключ хранится в системном хранилище. Роли настраиваются отдельно: разбор страницы можно оставить локальной модели, а длинный текст отдать облачной.': 'The key lives in the system store. Roles are separate: page parsing can stay local, a long draft can go to the cloud.',
  'Настройки → AI': 'Settings → AI',
  'Ollama и LM Studio': 'Ollama and LM Studio',
  'Если на машине уже поднят локальный сервер моделей, браузер найдёт его сам и предложит подключить.': 'If a local model server is already running, the browser finds it and offers to connect.',
  'Боковая AI-панель': 'Side AI panel',
  'Чат сбоку от страницы, у каждого окна свой. Знает, что открыто в текущей вкладке, и остаётся на месте при переключении вкладок.': 'Chat beside the page, one per window. It knows the current tab and stays put when you switch tabs.',
  'Значок в тулбаре': 'Icon in the toolbar',
  'Перевод страниц': 'Page translation',
  'Движок Bergamot на процессоре с локально скачанными языковыми парами; если пары нет — переводит модель. Готовые куски кэшируются.': 'Bergamot on the CPU with locally downloaded language pairs; if a pair is missing, the model translates. Finished chunks are cached.',
  'Поповер над выделением': 'Selection popover',
  'Выделили текст — перевести, пересказать, упростить или объяснить, не уходя со страницы.': 'Select text — translate, retell, simplify or explain without leaving the page.',

  'Правила, скиллы и агенты': 'Rules, skills and agents',
  'Настраиваемое поведение и обратное направление: браузер как инструмент для внешнего ИИ-клиента.': 'Adjustable behavior, and the other way around: the browser as a tool for an external AI client.',
  'Открывать ссылки с сайта в определённой группе, держать масштаб, не усыплять, включать VPN. Каталог намеренно маленький и закрытый.': 'Open a site’s links in a group, keep zoom, never sleep, turn VPN on. The catalog is small and closed on purpose.',
  'Настройки → Правила': 'Settings → Rules',
  'Свои кнопки для AI-панели: значок, имя и текст запроса. Появляются там же, где встроенные.': 'Your own AI-panel buttons: icon, name and prompt. They appear next to the built-in ones.',
  'Подключение внешнего агента': 'Connect an external agent',
  'Наша запись сама встраивается в конфиг вашего MCP-клиента (Claude Desktop, Cursor, Claude Code). Транспорт — именованный канал, а не открытый порт.': 'Our entry writes itself into your MCP client config (Claude Desktop, Cursor, Claude Code). Transport is a named pipe, not an open port.',
  'Подтверждение — в браузере': 'Confirm in the browser',
  'Вопрос «программе можно открыть эти вкладки?» задаёт сам браузер своим окном поверх всего. Три состояния на инструмент плюс белый список сайтов.': '“May this program open these tabs?” is asked by the browser itself, in its own window. Three states per tool plus a site allow-list.',
  'Карточка запроса': 'Request card',
  'Журнал обращений': 'Access log',
  'Кто подключался, какие инструменты звал и что получил — отдельный раздел библиотеки.': 'Who connected, which tools it called and what it got — a library section of its own.',
  'Библиотека → Агенты': 'Library → Agents',

  'Внешний вид и профили': 'Look and profiles',
  'Тема и палитра — две разные оси: первая отвечает «светло или темно», вторая — «какой оттенок нейтрали». Выбор палитры не отменяет выбор темы.': 'Theme and palette are two axes: light or dark, and which neutral tint. Picking a palette does not undo the theme.',
  'Светлая, тёмная, как в системе': 'Light, dark, system',
  'Переключается мгновенно, включая цвет шапки окна. В инкогнито тема всегда глубже обычной тёмной — это опознавательный знак режима.': 'Switches instantly, including the window header. In private mode the theme is always a deeper dark — that is how you recognize the mode.',
  'Настройки → Интерфейс': 'Settings → Appearance',
  'Четыре палитры': 'Four palettes',
  'Уголь, Графит, Сланец и Бумага. Палитра задаёт не только фон, но и акцент — то, чем красится выбранное и нажимаемое.': 'Charcoal, Graphite, Slate and Paper. The palette sets the ground and the accent — what selected and pressed things use.',
  'Разные наборы вкладок, закладок и логинов. Это удобство разделения, а не защита: чтобы не выйти из аккаунтов везде, основной профиль остаётся общим.': 'Separate sets of tabs, bookmarks and logins. Convenience, not a vault: the main profile stays shared so you do not sign out everywhere.',
  'Настройки → Профили': 'Settings → Profiles',
  'Новая версия скачивается в фоне и ставится при следующем запуске. Проверить вручную можно в любой момент.': 'A new version downloads in the background and installs on the next launch. You can check by hand any time.',

  'Вкладки и окна': 'Tabs and windows',
  'Новая вкладка — открывается хаб': 'New tab — opens the hub',
  'Закрыть активную вкладку': 'Close the active tab',
  'Вернуть последнюю закрытую': 'Reopen the last closed tab',
  'Следующая вкладка': 'Next tab',
  'Предыдущая вкладка': 'Previous tab',
  'Вкладка по номеру': 'Tab by number',
  'Последняя вкладка': 'Last tab',
  'Новое окно': 'New window',
  'Новая вкладка в инкогнито': 'New private tab',
  'Вернуть вкладку в другое окно': 'Move tab to another window',
  'Адрес, поиск, страница': 'Address, search, page',
  'Фокус в адресную строку': 'Focus the address bar',
  'Поповер быстрого поиска': 'Quick-search panel',
  'Обновить страницу': 'Reload the page',
  'Обновить мимо кэша': 'Reload ignoring cache',
  'Крупнее': 'Zoom in',
  'Мельче': 'Zoom out',
  'Сбросить масштаб': 'Reset zoom',
  'Данные и прочее': 'Data and other',
  'Сохранить страницу в закладки': 'Bookmark this page',
  'Открыть закладки': 'Open bookmarks',
  'Открыть библиотеку': 'Open the library',
  'Сохранить снимок — пока висит его карточка': 'Save the screenshot while its card is open',
  'Инструменты разработчика': 'Developer tools',

  'Не покидает машину': 'Stays on this computer',
  'История, закладки, загрузки и поиск по ним': 'History, bookmarks, downloads and search in them',
  'Перевод страниц и выделенного текста': 'Translation of pages and selected text',
  'Пересказ, объяснение, правка вашего черновика': 'Retelling, explaining, editing your draft',
  'Группировка вкладок и поиск вкладки по смыслу': 'Tab grouping and finding a tab by meaning',
  'Итоги дня, «вы это уже читали», разбор полей формы': 'Daily digest, “you already read this”, form-field parsing',
  'Блокнот, Студия и граф на локальной модели': 'Notebook, Studio and graph on the local model',
  'Расчёты приложений панели': 'Apps-panel calculations',
  'Уходит по вашему действию': 'Leaves on your action',
  'Запрос, который вы набрали в поисковике': 'The query you typed into a search engine',
  'Веб-поиск в хабе и фактчек': 'Hub web search and fact-check',
  'Облачная модель — только если вы вписали свой ключ': 'A cloud model — only if you pasted your own key',
  'Курсы валют, погода и цены отслеживаемых товаров': 'Exchange rates, weather and tracked product prices',
  'Списки блокировщика и проверка обновлений': 'Blocker lists and update checks',
  'Скачивание языковых пар и весов модели': 'Downloading language pairs and model weights',
  'Не собирается вовсе': 'Never collected',
  'Телеметрия и аналитика использования': 'Telemetry and usage analytics',
  'Отчёты о сбоях с содержимым страниц': 'Crash reports with page contents',
  'Профиль интересов и рекламные идентификаторы': 'Interest profiles and ad identifiers',
  'CVC банковской карты — не хранится нигде': 'Card CVC — not stored anywhere',
  'Внешние шрифты и CDN в интерфейсе': 'External fonts and CDNs in the UI',
  'Горячие клавиши': 'Keyboard shortcuts',
  'Что уходит наружу': 'What leaves the machine',
  'Что умеет браузер': 'What the browser can do',
  'функций': 'features',
  'функций в браузере': 'features in the browser',
  'Всё, что умеет Oblako, одним списком: что делает функция, где её найти и на какой клавише она живёт. Раздел ничего не настраивает — он отвечает на вопрос «а что тут вообще есть».': 'Everything Oblako can do, in one list: what a feature does, where to find it, and which key it uses. This section does not change settings — it answers “what is here at all”.',
  'Найти функцию: «сплит», «пароли», «перевод»…': 'Find a feature: “split”, “passwords”, “translate”…',
  'Найдено: {n}': 'Found: {n}',
  'Спорные аккорды намеренно оставлены странице: в Google Таблицах Ctrl+D — «заполнить вниз», и браузер не имеет права это отбирать.': 'Contested shortcuts stay with the page: in Google Sheets Ctrl+D fills down, and the browser must not steal that.',
  'Честная формулировка: не «ИИ только локальный», а «локальный там, где речь о вас». Телеметрии нет вообще, шрифты вшиты в приложение.': 'Said plainly: not “AI is only local”, but “local where it is about you”. No telemetry. Fonts are bundled.',
  'Oblako · Windows x64 · телеметрии нет': 'Oblako · Windows x64 · no telemetry',
};
