// Подписи разделов настроек. Заголовки блоков короткие: колонка навигации 200 px,
// пилюли SegTrack и карточки Fact не должны разъезжаться на английском.
export const SETTINGS: Record<string, string> = {
  'Всегда светлый интерфейс': 'Always light',
  'Всегда тёмный интерфейс': 'Always dark',
  'Следует переключателю Windows': 'Follows Windows',
  'Градиент': 'Gradient',
  'Свой градиент': 'Custom gradient',
  'Свой цвет': 'Custom color',
  'Своё фото': 'My photo',
  'Фото дня': 'Daily photo',
  'Как в iOS': 'Like iOS',
  'Как в macOS': 'Like macOS',
  'Холодный': 'Cool',
  'Тёплый': 'Warm',
  'Зелёная земля': 'Green ground',
  'Голубая земля': 'Blue ground',
  'Файл больше 8 МБ': 'File is over 8 MB',
  'Не удалось прочитать файл': 'Could not read the file',
  'оттенок нейтрали': 'neutral tint',
  'Ровный': 'Flat',
  'Краска': 'Paint',
  'Тон палитры': 'Palette tone',
  'облик всего браузера — окно, поповеры и новая вкладка': 'window, popovers and new tab',
  'Тема и палитра браузера, оформление новой вкладки — фон, часы, приветствие и быстрые ссылки.': 'Theme and palette of the browser, plus the new-tab background, clock and shortcuts.',
  'светлая, тёмная или вслед за системой': 'light, dark, or match Windows',
  'Фон окна': 'Window ground',
  'мягкий градиент и текстура': 'soft gradient and grain',
  'ровная заливка палитры': 'flat palette fill',
  'Новая вкладка': 'New tab',
  'что стоит фоном': 'current background',
  'Светлая, тёмная или вслед за системой. Образец показывает выбранную палитру.': 'Light, dark, or match Windows. The sample uses the selected palette.',
  'Приватные вкладки остаются тёмными при любой теме.': 'Private tabs stay dark in every theme.',
  'Оттенок нейтрали: фон, поверхности и текст. Акцентный цвет не меняется.': 'Neutral tint for ground, surfaces and text. The accent color stays the same.',
  'Фон интерфейса': 'Window background',
  'Мягкий градиент и лёгкая текстура на всём окне вместо ровной заливки. Можно взять тон палитры или свой градиент из общего каталога.': 'A soft gradient and light grain across the window instead of a flat fill. Use the palette tone or a custom gradient.',
  'Цветной фон': 'Tinted ground',
  'Ровная заливка': 'Flat fill',
  'Мягкий градиент и лёгкая текстура на всём окне': 'Soft gradient and light grain across the window',
  'Окно залито ровным фоном палитры': 'The window uses a flat palette fill',
  'Создать градиент': 'New gradient',
  'Случайный': 'Random',
  'Насыщенность': 'Tint',
  'Фон': 'Background',
  'Градиент, свой цвет или изображение. Свои градиенты те же, что у фона интерфейса.': 'Gradient, a custom color, or an image. Custom gradients are shared with the window background.',
  'Цвет': 'Color',
  'Картинка дня Wikimedia — отбирают редакторы Commons. Загружается через ваше соединение или VPN и кэшируется на день.': 'Wikimedia picture of the day, chosen by Commons editors. It loads through your connection or VPN and is cached for the day.',
  'Другое фото': 'Another photo',
  'Заменить фото': 'Replace photo',
  'Выбрать фото': 'Choose photo',
  'Убрать': 'Remove',
  'Изображение хранится локально на этом устройстве.': 'The image stays on this device.',
  'Затемнение': 'Dim',
  'Размытие': 'Blur',
  'Часы': 'Clock',
  'Вид и формат виджета часов на новой вкладке.': 'Face and format of the clock widget on the new tab.',
  'Циферблат': 'Analog',
  'Цифры': 'Digital',
  '24-часовой формат': '24-hour clock',
  'Иначе 12 часов с AM и PM': 'Otherwise 12-hour with AM/PM',
  'Секунды': 'Seconds',
  'Секундная стрелка': 'Second hand',
  'Обновление раз в секунду вместо раза в минуту': 'Updates every second instead of every minute',
  'Дата и день недели': 'Date and weekday',
  'Строка под временем': 'Line under the time',
  'Строка поиска на самой новой вкладке — адресная строка работает независимо от неё.': 'Search field on the new tab. The address bar is separate.',
  'Строка поиска': 'Search field',
  'Поле по центру новой вкладки': 'Centered field on the new tab',
  'Погода': 'Weather',
  'Город для виджета погоды на новой вкладке.': 'City for the weather widget on the new tab.',
  'Город (например, Москва)': 'City (for example, London)',
  'Курс валют': 'Exchange rates',
  'Какие валюты показывает виджет курса (данные ЦБ РФ).': 'Currencies shown by the rates widget (Central Bank of Russia).',
  'Крипта': 'Crypto',
  'Какие активы показывает виджет «Крипта» (цены в рублях, источник — CoinGecko).': 'Assets shown by the Crypto widget (prices in rubles, CoinGecko).',
  'Градиент фона интерфейса': 'Window gradient',
  'Градиент новой вкладки': 'New-tab gradient',
  'Сейчас в Windows тёмная': 'Windows is dark now',
  'Сейчас в Windows светлая': 'Windows is light now',
  'Удалить': 'Delete',
  'Доллар': 'Dollar',
  'Евро': 'Euro',
  'Юань': 'Yuan',
  'Фунт': 'Pound',
  'Иена': 'Yen',
  'Тенге': 'Tenge',
  'Лира': 'Lira',
  'Бел. рубль': 'Belarusian ruble',
  'Драм': 'Dram',
  'Лари': 'Lari',
  'Мандарин': 'Tangerine',
  'Горчица': 'Mustard',
  'Лайм': 'Lime',
  'Чай': 'Tea',
  'Страсть': 'Passion',
  'Океан': 'Ocean',
  'Изумруд': 'Emerald',
  'Пламя': 'Ember',
  'Персик': 'Peach',
  'Жемчуг': 'Pearl',
  'Бумага светлая': 'Light paper',
  'Бумага тень': 'Paper shade',
  'Мелкий': 'Small',
  'Средний': 'Medium',
  'Крупный': 'Large',

  'Блокировка рекламы': 'Ad blocking',
  'запрос заблокирован за сеанс': 'request blocked this session',
  'запросов заблокировано за сеанс': 'requests blocked this session',
  'Обновить открытые вкладки, чтобы применить изменения?': 'Reload open tabs to apply the change?',
  'Обновить вкладки {n}?': 'Reload {n} tabs?',
  'Блокировка включена': 'Blocking is on',
  'Блокировка выключена': 'Blocking is off',
  'Реклама и трекеры режутся на всех сайтах, кроме исключений ниже': 'Ads and trackers are cut on every site except the exceptions below',
  'Сайты грузятся как есть — со всей рекламой и счётчиками': 'Sites load as they are — ads and trackers included',
  'Трекеры': 'Trackers',
  'Скрытая слежка за переходами': 'Hidden tracking of your visits',
  'Режем': 'Blocked',
  'Пропускаем': 'Allowed',
  'Баннеры': 'Banners',
  'Сетевой блок и косметика': 'Network block and cosmetic filters',
  'Исключения': 'Exceptions',
  'Сайты, где реклама разрешена': 'Sites where ads are allowed',
  'Нет': 'None',
  'сайт': 'site',
  'сайта': 'sites',
  'сайтов': 'sites',
  'Списки фильтров': 'Filter lists',
  'EasyList и EasyPrivacy': 'EasyList and EasyPrivacy',
  '2 списка': '2 lists',
  'Убрать из исключений': 'Remove from exceptions',
  'Добавить сайт': 'Add site',
  'Домен или адрес сайта': 'Domain or site address',

  'Выключен': 'Off',
  'Подключаюсь': 'Connecting',
  'Подключено': 'Connected',
  'Ошибка': 'Error',
  'Введите ссылку подписки': 'Enter a subscription URL',
  'Загружено серверов: {n}': 'Servers loaded: {n}',
  ', не распознано: {n}': ', skipped: {n}',
  'Не удалось сохранить': 'Could not save',
  'Обновлено. Серверов: {n}': 'Updated. Servers: {n}',
  'Не удалось обновить': 'Could not update',
  'трафик браузера идёт через сервер': 'browser traffic goes through the server',
  'туннель не поднялся': 'tunnel did not start',
  'трафик идёт напрямую': 'traffic goes direct',
  'Туннель упал — сеть закрывается': 'If the tunnel drops, the network closes',
  'Сторожит': 'Watching',
  'В покое': 'Idle',
  'Локальный адрес не утекает': 'Your real address does not leak',
  'Закрыт': 'Closed',
  'Как обычно': 'As usual',
  'Серверы': 'Servers',
  'обновлено {date}': 'updated {date}',
  'подписка не добавлена': 'no subscription',
  'Протокол': 'Protocol',
  'Xray-core дочерним процессом': 'Xray-core as a child process',
  'Подписка сохранена': 'Subscription saved',
  'Подписка не добавлена': 'No subscription',
  'серверов: {n}': 'servers: {n}',
  'Обновление…': 'Updating…',
  'Сохранение…': 'Saving…',
  'Сохранить': 'Save',
  'подключён': 'connected',
  'подключаюсь…': 'connecting…',
  'ошибка': 'error',
  'Подключение…': 'Connecting…',
  'Вставить ссылку подписки': 'Paste subscription URL',
  'Kill switch': 'Kill switch',
  'WebRTC': 'WebRTC',
  'Ссылка подписки': 'Subscription URL',
  'Выбрать сервер': 'Choose server',
  'Подключить VPN': 'Connect VPN',
  'Отключить': 'Disconnect',

  'Сохранённые пароли': 'Saved passwords',
  'Перенести из другого браузера': 'Import from another browser',
  'Зашифрованная копия сейфа': 'Encrypted vault copy',
  'Показать пароль': 'Show password',
  'Скопировать пароль': 'Copy password',
  'Скопировать логин': 'Copy username',
  'Удалить пароль': 'Delete password',
  'Добавить пароль': 'Add password',
  'Сайт': 'Site',
  'Логин': 'Username',
  'Пароль': 'Password',
  'Поиск по паролям': 'Search passwords',
  'Пока нет сохранённых паролей.': 'No saved passwords yet.',
  'Windows Hello': 'Windows Hello',
  'Чтобы увидеть пароль или номер карты, система спросит подтверждение.': 'Showing a password or card number asks Windows to confirm it is you.',
  'Копия сейфа': 'Vault copy',
  'Парольная фраза': 'Passphrase',

  'Адреса': 'Addresses',
  'Банковские карты': 'Payment cards',
  'Добавить адрес': 'Add address',
  'Добавить карту': 'Add card',
  'Имя': 'Name',
  'Телефон': 'Phone',
  'Индекс': 'Postal code',
  'Страна': 'Country',
  'Номер карты': 'Card number',
  'Срок': 'Expiry',
  'Пока нет сохранённых адресов.': 'No saved addresses yet.',
  'Пока нет сохранённых карт.': 'No saved cards yet.',

  'Сайты': 'Sites',
  'Сертификаты Минцифры': 'Ministry of Digital certificates',
  'камера': 'camera',
  'микрофон': 'microphone',
  'геолокация': 'location',
  'уведомления': 'notifications',
  'Разрешено': 'Allowed',
  'Запрещено': 'Denied',
  'Спросить': 'Ask',
  'Забыть': 'Forget',
  'Нет сохранённых решений.': 'No saved decisions yet.',

  'Ваши профили': 'Your profiles',
  'При запуске браузера': 'When the browser starts',
  'Создать профиль': 'New profile',
  'Переименовать': 'Rename',
  'Спрашивать, какой профиль открыть': 'Ask which profile to open',
  'Всегда этот': 'Always this one',

  'Правила-автоматизации': 'Automation rules',
  'Новое правило': 'New rule',
  'Пока правил нет.': 'No rules yet.',
  'Включить': 'Turn on',
  'Выключить': 'Turn off',

  'Локальные модели': 'Local models',
  'Движок перевода страниц': 'Page translation engine',
  'Индексация истории для поиска': 'History index for search',
  'Скиллы': 'Skills',
  'Фактчек и веб-поиск': 'Fact-check and web search',
  'Готова': 'Ready',
  'В памяти': 'In memory',
  'не установлена': 'not installed',
  'Рекомендуем': 'Recommended',
  'Помощнее': 'Larger',
  'При старте браузера': 'At browser start',
  'При первом обращении': 'On first use',
  'Модель готова сразу, занимает ~6 ГБ оперативной памяти постоянно.': 'Ready immediately; keeps about 6 GB of RAM.',
  'Экономит память, первый ответ займёт около 30 секунд.': 'Saves memory; the first reply takes about 30 seconds.',
  'Выгружать после 40 минут простоя': 'Unload after 40 minutes idle',
  'Освобождает видеопамять, когда ИИ не нужен. Выключите, если не хотите ждать загрузки при следующем обращении.': 'Frees video memory when AI is idle. Turn off if you do not want to wait next time.',
  'Проверяю…': 'Checking…',
  'Проверить снова': 'Check again',
  'Видеокарта не обнаружена': 'No GPU found',
  'Локальный AI на этом устройстве не потянет': 'Local AI will not run on this device',
  'Локальные модели считаются на видеокарте, а браузер её сейчас не видит — поэтому список моделей пуст. Обычно помогает обновление драйвера видеокарты и перезапуск браузера.': 'Local models run on the GPU, and the browser cannot see one, so the list is empty. Updating the GPU driver and restarting usually helps.',
  'Нужна видеокарта минимум с 4 ГБ памяти.': 'A GPU with at least 4 GB of memory is required.',
  'Всё остальное — вкладки, блокировка рекламы, VPN, пароли — работает как обычно.': 'Everything else — tabs, ad blocking, VPN, passwords — still works.',
  'Модель для AI-перевода, чата и остальных функций хранится и считается на этом устройстве. Без хотя бы одной установленной модели остальные AI-функции не работают.': 'The model for translation, chat and the other AI features stays on this device. Without at least one installed model the rest of the AI features do not run.',
  'Выгружаю…': 'Unloading…',
  'Выгрузить сейчас': 'Unload now',
  'Нет установленных моделей.': 'No models installed.',
  'видеопамять: {n}': 'video memory: {n}',
  'файл вне папки приложения': 'file outside the app folder',
  'последняя оставшаяся модель': 'last remaining model',
  'активна': 'active',
  'в памяти': 'in memory',
  'Выгрузить': 'Unload',
  'Да': 'Yes',
  'Удалить модель': 'Delete model',
  'Удаляю…': 'Deleting…',
  'Скачиваю {id}: {got} из {total} ГБ ({pct}%)': 'Downloading {id}: {got} of {total} GB ({pct}%)',
  'вне папки приложения': 'outside the app folder',
  'Модель уже не найдена в реестре (возможно, удалена в другом месте).': 'The model is no longer in the registry. It may have been deleted elsewhere.',
  'Эта модель лежит вне папки приложения — удалить её отсюда нельзя.': 'This model sits outside the app folder, so it cannot be deleted from here.',
  'Нельзя удалить последнюю оставшуюся модель.': 'The last remaining model cannot be deleted.',
  'Ошибка файловой системы при удалении файла модели.': 'A filesystem error occurred while deleting the model file.',
  'Не удалось удалить модель.': 'Could not delete the model.',
  'ГБ загрузки · нужно {n} ГБ видеопамяти': 'GB download · {n} GB video memory needed',
  'ни одного GPU-устройства': 'no GPU device',
  'детект не выполнился': 'detection did not run',
  'Определено: {what}': 'Detected: {what}',
  'Агенты': 'Agents',
  'Модели': 'Models',
  'EasyList и EasyPrivacy на уровне сетевых запросов — быстрее расширений браузера.': 'EasyList and EasyPrivacy at the network layer — faster than browser extensions.',
  'На этих сайтах реклама блокироваться не будет. Домен покрывает и все поддомены (например, www.example.com).': 'Ads will not be blocked on these sites. A domain covers all subdomains (for example, www.example.com).',
  'Добавить': 'Add',
  'Ссылка подписки и серверы хранятся зашифрованными на этом устройстве и никуда, кроме вашего провайдера, не отправляются.': 'The subscription URL and servers stay encrypted on this device and go only to your provider.',
  'Нажмите на сервер, чтобы подключиться.': 'Click a server to connect.',
  'Серверы ({n})': 'Servers ({n})',
};
