// Меню, ошибки, виджеты, поповеры, хаб. Подписи хрома — короткие, чтобы не ломать пилюли и пункты.
export const CHROME: Record<string, string> = {
  'Открыть ссылку в новой вкладке': 'Open link in new tab',
  'Открыть ссылку в новом окне': 'Open link in new window',
  'Открыть ссылку в инкогнито': 'Open link in private tab',
  'Открыть ссылку в split': 'Open link in split',
  'Копировать адрес ссылки': 'Copy link address',
  'Копировать картинку': 'Copy image',
  'Сохранить картинку': 'Save image',
  'Сохранить картинку как…': 'Save image as…',
  'Открыть картинку в новой вкладке': 'Open image in new tab',
  'Править текст': 'Edit text',
  'Исправить ошибки': 'Fix mistakes',
  'Сделать короче': 'Make shorter',
  'Смягчить тон': 'Soften tone',
  'Перевести на': 'Translate to',
  'Перевести': 'Translate',
  'Пересказать проще': 'Simplify',
  'Объяснить': 'Explain',
  'Краткая выжимка': 'Summarize',
  'Обновить без кэша': 'Reload ignoring cache',
  'Просмотреть код': 'Inspect',
  'Поиск «{q}» в {engine}': 'Search “{q}” with {engine}',
  'Искать…': 'Search…',

  'Отслеживание цены': 'Track price',
  'Отслеживание': 'Tracking',
  'Не отслеживать': 'Stop tracking',
  'Отслеживать цену': 'Track price',
  'Что я отслеживаю': 'What I track',
  'Сейчас {price}': 'Now {price}',
  'Открепить вкладку': 'Unpin tab',
  'Закрепить вкладку': 'Pin tab',
  'Включить звук': 'Unmute',
  'Выключить звук': 'Mute',
  'Придумать название заново': 'Rename again',
  'Придумать название по смыслу': 'Rename by meaning',
  'Группа': 'Group',
  'Показать оригинал': 'Show original',
  'Перевести страницу': 'Translate page',
  'Папка': 'Folder',
  'Положить в «{name}»': 'Move to “{name}”',
  'Без названия': 'Untitled',
  'Копировать': 'Copy',
  'Дублировать вкладку': 'Duplicate tab',
  'Открыть в новом окне': 'Open in new window',
  'Вернуть заголовок страницы': 'Restore page title',
  'Не выгружать из памяти': 'Keep in memory',
  'Убрать из группы': 'Remove from group',
  'Создать группу': 'New group',
  'Добавить в группу': 'Add to group',
  'Закрыть вкладку': 'Close tab',
  'Новая вкладка инкогнито': 'New private tab',
  'Открыть закрытую вкладку': 'Reopen closed tab',
  'Без цвета': 'No color',
  'Красный': 'Red',
  'Оранжевый': 'Orange',
  'Жёлтый': 'Yellow',
  'Зелёный': 'Green',
  'Синий': 'Blue',
  'Фиолетовый': 'Purple',
  'Цвет': 'Color',
  'Свернуть / развернуть': 'Collapse / expand',
  'Скопировать содержимое': 'Copy contents',
  'Расформировать группу': 'Ungroup',
  'Закрыть группу и вкладки': 'Close group and tabs',
  'Сохранено в закладки': 'Bookmarked',
  'Все закладки': 'All bookmarks',
  'В новый граф…': 'New graph…',
  'Добавить в граф': 'Add to graph',
  'Новая группа': 'New group',
  'главное окно': 'main window',
  'окно {n}': 'window {n}',
  'Вернуть в {name}': 'Move to {name}',
  'Перенести в окно': 'Move to window',
  'Придумываю название…': 'Naming…',

  'Такого сайта не нашлось': 'This site was not found',
  'Мы спросили адрес {host}, но в справочнике DNS о нём не слышали.': 'We asked for {host}, but DNS has never heard of it.',
  'Чаще всего виновата опечатка в адресе. Если адрес точно верный — сайт мог переехать или закрыться.': 'Usually this is a typo. If the address is right, the site may have moved or closed.',
  'Интернета нет': 'No internet',
  'Браузер вообще не видит сети — дело не в сайте.': 'The browser cannot see a network at all — it is not the site.',
  'Проверьте Wi-Fi или кабель и обновите страницу.': 'Check Wi-Fi or the cable, then reload.',
  'Сервер не открыл дверь': 'The server refused',
  '{host} получил запрос и ответил отказом.': '{host} got the request and refused it.',
  'Обычно так выглядит сайт, который лёг или закрыт для внешних подключений. Имеет смысл зайти позже.': 'Usually the site is down or closed to outside connections. Try again later.',
  'Связь оборвалась': 'The connection broke',
  'Разговор с {host} прервался на полуслове.': 'The conversation with {host} stopped mid-sentence.',
  'Почти всегда лечится обновлением. Если повторяется — виновата сеть между вами и сайтом.': 'A reload almost always helps. If it repeats, the network between you and the site is at fault.',
  'Сайт молчит': 'The site is silent',
  '{host} не прислал ответ за отведённое время.': '{host} did not answer in time.',
  'Похоже, он перегружен или недоступен из вашей сети. Попробуйте обновить или вернуться позже.': 'It looks overloaded or unreachable from your network. Reload or come back later.',
  'До этого адреса нет дороги': 'No route to this address',
  'Из вашей сети до {host} не проложить маршрут.': 'Your network cannot route to {host}.',
  'Так бывает при проблемах с роутером или когда сайт закрыт для вашего региона — здесь может выручить VPN.': 'This happens with a broken router, or when the site is closed in your region — VPN may help.',
  'Это остановил сам браузер': 'The browser stopped this',
  'Попробовать снова': 'Try again',
  'Назад': 'Back',

  'Календарь': 'Calendar',
  'Месяц целиком': 'The whole month',
  'Таймер': 'Timer',
  '5, 10 или 20 минут': '5, 10 or 20 minutes',
  'Карточки': 'Cards',
  '80 слов · язык в настройках экрана': '80 words · language in screen settings',
  'Прогноз на ближайшие часы': 'Forecast for the next hours',
  'Ясно': 'Clear',
  'Малооблачно': 'Partly cloudy',
  'Пасмурно': 'Overcast',
  'Туман': 'Fog',
  'Морось': 'Drizzle',
  'Дождь': 'Rain',
  'Снег': 'Snow',
  'Ливень': 'Downpour',
  'Снегопад': 'Snowfall',
  'Гроза': 'Storm',
  'хорошо': 'good',
  'нормально': 'fair',
  'средне': 'moderate',
  'плохо': 'poor',
  'очень плохо': 'very poor',
  'Не удалось загрузить': 'Could not load',
  'Укажите город в настройках интерфейса': 'Set a city in Appearance',
  ', ощущается {n}°': ', feels {n}°',
  'Воздух: {n} · {label}': 'Air: {n} · {label}',
  'Погода…': 'Weather…',
  'Погода недоступна: {error}': 'Weather unavailable: {error}',
  ' · ветер {n} км/ч': ' · wind {n} km/h',
  'город не задан': 'no city set',
  'город «{query}» не найден': 'city “{query}” not found',
  'Свои данные': 'On this device',
  'Работают офлайн, ничего никуда не отправляют': 'Work offline, send nothing',
  'Внешние сервисы': 'External services',
  'Каждый обращается к указанному сайту': 'Each one talks to the named site',
  'Настройка экрана': 'Desk settings',
  'Доллар и евро, график за месяц': 'Dollar and euro, month chart',
  'Цены в рублях и за 24 часа': 'Prices in rubles, last 24 hours',
  'Дела': 'Tasks',
  'Список с галочками': 'A checklist',
  'Часто открываете': 'Frequent sites',
  'Сайты из вашей истории': 'Sites from your history',
  'Музыка': 'Music',
  'Управление тем, что играет · обложка грузится с сервиса': 'Controls what is playing · cover loads from the service',
  'Защита': 'Shield',
  'Адблок и VPN': 'Ad block and VPN',
  'Луна': 'Moon',
  'Фаза по дате': 'Phase by date',
  'Что качается': 'What is downloading',
  'Праздники': 'Holidays',
  'Сколько до ближайшего': 'Time until the next one',
  'Чем занимался': 'What I did',
  'Итог дня по вашей истории': 'A daily recap from your history',
  'Цены товаров': 'Product prices',
  'Время и дата': 'Time and date',
  'Добавить виджет': 'Add widget',
  'Добавить сайт': 'Add site',
  'Приложения': 'Apps',
  'Поиск виджетов': 'Search widgets',
  'Уже на столе': 'Already on the desk',
  'ЦБ РФ': 'CBR',
  'Что поставим?': 'Add to the desk',
  'Поиск в виджетах': 'Search widgets',
  'Ничего не нашлось — попробуйте другое слово.': 'Nothing found — try another word.',
  'Всё уже на экране.': 'Everything is already on the screen.',
  'Сайт': 'Site',
  'Адрес, например github.com': 'Address, e.g. github.com',
  'Название (необязательно)': 'Name (optional)',
  '{hint} · данные у {service}': '{hint} · data from {service}',
  'Сегодня': 'Today',
  'Вчера': 'Yesterday',
  'Раньше': 'Earlier',
  'Поиск по истории': 'Search history',
  'Поиск по закладкам': 'Search bookmarks',
  'Поиск по загрузкам': 'Search downloads',
  'Папки': 'Folders',
  'Без папки': 'No folder',
  'Новая папка': 'New folder',
  'Открыть файл': 'Open file',
  'Показать в папке': 'Show in folder',
  'Отменить загрузку': 'Cancel download',
  'Удалить из списка': 'Remove from list',
  'Повторить загрузку': 'Retry download',
  'Пауза': 'Pause',
  'Продолжить': 'Resume',
  'Готово': 'Done',
  'Ошибка загрузки': 'Download failed',
  'Уже скачано': 'Already downloaded',
  'Очистить историю': 'Clear history',
  'За этот период записей нет.': 'Nothing in this period.',
  'Закладок пока нет.': 'No bookmarks yet.',
  'Загрузок пока нет.': 'No downloads yet.',

  'Доступ': 'Access',
  'Сайт просит доступ': 'This site is asking for access',
  'Запомнить выбор': 'Remember this choice',
  'Камера': 'Camera',
  'Микрофон': 'Microphone',
  'Геолокация': 'Location',
  'Уведомления': 'Notifications',

  'Реклама': 'Ads',
  'На этом сайте': 'On this site',
  'Открыть настройки': 'Open settings',
  'Подключение': 'Connection',
  'Сервер': 'Server',
  'Выбрать': 'Choose',
  'Скачивается': 'Downloading',
  'Ожидает': 'Waiting',
  'Скопировать': 'Copy',
  'Вставить': 'Paste',
  'Вырезать': 'Cut',
  'Выделить всё': 'Select all',
  'Очистить': 'Clear',
  'Пусто': 'Empty',
  'Только что': 'Just now',
  'Перевод': 'Translation',
  'Пересказ': 'Retell',
  'Упростить': 'Simplify',
  'Отправить': 'Send',
  'Спросить о странице…': 'Ask about this page…',
  'Саммари': 'Summary',
  'Фактчек': 'Fact-check',
  'Сделать саммари': 'Summarize',
  'Страница': 'Page',
  'Нет выделения': 'Nothing selected',
  'Модель думает…': 'The model is thinking…',
  'Не удалось перевести': 'Could not translate',
  'Снимок': 'Screenshot',
  'Сохранить как…': 'Save as…',
  'Копировать снимок': 'Copy screenshot',
  'Процессы': 'Processes',
  'Память': 'Memory',
  'ЦП': 'CPU',
  'Диспетчер задач': 'Task manager',

  'Справка: что умеет браузер': 'Help: what the browser can do',
  'Горячие клавиши': 'Keyboard shortcuts',
  'Что уходит наружу, а что нет': 'What leaves the machine, and what does not',
  'Импорт данных из другого браузера': 'Import from another browser',
  'Строка поиска на новой вкладке': 'Search field on the new tab',
  'Фон новой вкладки': 'New-tab background',
  'Локальная модель': 'Local model',
  'Профиль при запуске': 'Profile at launch',
  'Копия сейфа': 'Vault copy',
  'Запрос не ушёл наружу — его перехватила защита.': 'The request never left — protection intercepted it.',
  'Скорее всего сработал встроенный блокировщик. Отключите его для этого сайта в поповере «Защита» и обновите страницу.': 'The built-in blocker likely fired. Turn it off for this site in the Protection popover and reload.',
  'Сеть сменилась на полпути': 'The network changed midway',
  'Подключение переключилось, пока страница грузилась.': 'The connection switched while the page was loading.',
  'Обычное дело при включении или отключении VPN. Достаточно обновить.': 'Common when turning VPN on or off. A reload is enough.',
  'Прокси не отвечает': 'The proxy is not answering',
  'Подключиться через прокси-сервер не вышло.': 'Connecting through the proxy failed.',
  'Если включён VPN — загляните в поповер «Защита»: сервер мог отвалиться, а kill switch не пускает трафик в обход.': 'If VPN is on, check the Protection popover: the server may have dropped, and kill switch is blocking a bypass.',
  'Страница зациклилась': 'The page looped',
  '{host} перекидывает с адреса на адрес по кругу.': '{host} keeps sending you from address to address.',
  'Часто помогает очистить куки этого сайта. Если нет — он сломан на своей стороне.': 'Clearing cookies for this site often helps. If not, it is broken on their side.',
  'Ответ пришёл пустым': 'The reply was empty',
  '{host} закрыл соединение, не передав ни байта.': '{host} closed the connection without sending a byte.',
  'Обычно это временный сбой на стороне сайта — попробуйте обновить.': 'Usually a temporary fault on the site — try reloading.',
  'Этот порт закрыт': 'This port is closed',
  'Chromium не открывает адреса на таком порту.': 'Chromium will not open addresses on that port.',
  'Список запрещённых портов зашит в движок ради безопасности — почта, FTP и подобные. Обойти его из браузера нельзя.': 'The blocked-port list is built into the engine for safety — mail, FTP and the like. The browser cannot bypass it.',
  'Адрес не разобрать': 'The address cannot be parsed',
  'Такую строку нельзя открыть как ссылку.': 'That string cannot be opened as a link.',
  'Проверьте адрес: возможно, в нём лишний символ или незнакомая схема.': 'Check the address: there may be an extra character or an unknown scheme.',
  'Файла нет на месте': 'The file is not there',
  'По этому пути на диске ничего не лежит.': 'Nothing sits at that path on disk.',
  'Его могли переместить, переименовать или удалить.': 'It may have been moved, renamed or deleted.',
  'Защищённое соединение не сложилось': 'The secure connection failed',
  'Договориться о шифровании с {host} не удалось.': 'Could not agree encryption with {host}.',
  'Либо сайт настроен неправильно, либо соединение кто-то подменяет. Пароли на нём сейчас вводить не стоит.': 'The site may be misconfigured, or the connection is being intercepted. Do not enter passwords there now.',
  'С сертификатом что-то не так': 'Something is wrong with the certificate',
  'Браузер не доверяет сертификату {host} (код {code}).': 'The browser does not trust the certificate of {host} (code {code}).',
  'Он мог истечь или быть выписан на другой домен. Пока причина не ясна, не вводите здесь пароли и данные карт.': 'It may have expired or been issued for another domain. Until that is clear, do not enter passwords or card details here.',
  'Страница не открылась': 'The page did not open',
  'Загрузка прервалась с кодом {code}.': 'Loading stopped with code {code}.',
  'Попробуйте обновить. Если повторится — проблема, скорее всего, на стороне сайта.': 'Try reloading. If it repeats, the problem is likely on the site.',
  'Вкладка не выдержала': 'The tab crashed',
  'Процесс, который рисовал эту страницу, завершился сам собой.': 'The process that drew this page ended on its own.',
  'Остальные вкладки целы — эту достаточно перезагрузить.': 'The other tabs are fine — reload this one.',
  'Сайту не доверились': 'This site was not trusted',
  'Сайт подтверждает себя сертификатом удостоверяющего центра Минцифры. Браузер доверяет этому центру только для сайтов, которым это разрешили, — по умолчанию для банков, у которых другого сертификата не бывает. Вы ответили «не открывать».': 'The site identifies itself with a Ministry of Digital CA certificate. The browser trusts that CA only for sites you allowed — by default banks that have no other certificate. You answered “do not open”.',
  'Если отказались по ошибке — перезапустите браузер и откройте адрес ещё раз: вопрос появится снова. Разрешать стоит, только если вы узнаёте адрес и пришли сюда сами.': 'If you refused by mistake, restart the browser and open the address again: the question will return. Allow it only if you recognize the address and came here yourself.',
  'Кажется, интернет пропал': 'The internet seems gone',
  'В момент загрузки браузер не видел сети.': 'The browser saw no network at the moment of loading.',
  'Проверьте Wi-Fi или кабель. Если пользуетесь VPN — убедитесь, что он подключён.': 'Check Wi-Fi or the cable. If you use VPN, make sure it is connected.',
  'Профиль ждёт VPN': 'This profile needs VPN',
  'Профиль «{name}» настроен открывать сайты только через VPN, а туннель сейчас выключен.': 'Profile “{name}” is set to open sites only through VPN, and the tunnel is off.',
  'Включите VPN в поповере «Защита» — или смените выход в сеть у профиля в настройках.': 'Turn VPN on in the Protection popover — or change the profile’s network setting.',
  'Подключаю…': 'Connecting…',
  'Включить VPN': 'Turn VPN on',
  'Сначала добавьте подписку в настройках VPN': 'Add a VPN subscription in Settings first',
  'Не удалось подключиться': 'Could not connect',
};
