// Остаток подписей настроек, библиотеки и поповеров.
// Заголовки короткие: колонка 200 px и пилюли не должны разъезжаться.
export const MORE: Record<string, string> = {
  'AI-перевод (медленно, выше качество)': 'AI translate (slower)',
  'Bergamot (быстрее, легче)': 'Bergamot (faster)',
  'Bergamot, без сети': 'Bergamot, offline',
  'Bitwarden и другие': 'Bitwarden and others',
  'CSV-экспорт паролей': 'CSV password export',
  'Chrome, Edge, Firefox, Яндекс.Браузер': 'Chrome, Edge, Firefox, Yandex',
  'Enter в Ctrl+E всегда уходит в поисковик': 'Enter in Ctrl+E always goes to search',
  'Gemini, облачный': 'Gemini, cloud',
  'Qwen — универсальная модель, переводит любой язык, медленнее на CPU/GPU.': 'Qwen translates any language; slower on CPU/GPU.',
  'SearXNG — веб-поиск для AI': 'SearXNG web search',
  'SearXNG, свой сервер': 'SearXNG, your server',
  'VPN и блокировка — на профиль': 'VPN and blocking per profile',
  '«Забыть» вернёт вопрос: сайт спросит снова при следующей попытке. «Запретить» закрывает вопрос насовсем.': 'Forget asks again next time. Deny closes the question for good.',
  'Адресов пока нет': 'No addresses yet',
  'Больше не спрашиваем': 'Do not ask again',
  'Браузер как инструмент': 'Browser as a tool',
  'Браузер работает на модели этой машины. Подключение нужно там, где ответ сочиняют: чат, работа со страницы, блокнот.': 'The browser runs on this machine’s model. A connection is for chat, page work and the notebook.',
  'Браузер работает на модели этой машины. Подключение нужно там, где ответ сочиняют: чат, работа со страницей, блокнот.': 'The browser runs on this machine’s model. A connection is for chat, page work and the notebook.',
  'Бэнг удалили или сайт вытеснили из выученных — поповер откроется как обычно': 'The bang or site is gone — the popover opens as usual',
  'Веб-поиск': 'Web search',
  'Вернуть поведение по умолчанию': 'Restore defaults',
  'Владелец карты': 'Cardholder',
  'Внешний ИИ — Claude Desktop, Claude Code, Cursor — может спросить у браузера, что у вас открыто, прочитать текст страницы и поискать в истории. По протоколу MCP, только на этой машине.': 'An external AI can ask what is open, read the page and search history. MCP, this machine only.',
  'Внешний менеджер': 'External manager',
  'Вставьте адрес одной строкой — разложим по полям': 'Paste an address in one line — we will split the fields',
  'Встроенные': 'Built-in',
  'Год (ГГ или ГГГГ)': 'Year',
  'Город': 'City',
  'Два аккаунта одного сайта рядом': 'Two accounts for the same site',
  'Длина': 'Length',
  'Для страниц, которые вы больше не откроете (например перенесённых из другого браузера). Тихо переоткрывает их в фоне и забирает текст. На большой истории занимает время, остановить можно в любой момент.': 'For pages you will not reopen (including imports). Opens them in the background and reads the text. On a large history this takes time; you can stop it.',
  'Добавить цель в полосу…': 'Add a target…',
  'Добавьте один — и формы заказа будут заполняться сами. Данные шифруются на этом компьютере и наружу не уходят.': 'Add one and checkout forms fill themselves. Data stays encrypted on this computer.',
  'Доступно': 'Available',
  'Есть сохранённое решение': 'A decision is saved',
  'Забыть все решения по этому сайту': 'Forget all decisions for this site',
  'Загрузок пока нет': 'No downloads yet',
  'Заметки (необязательно)': 'Notes (optional)',
  'Запросов': 'Requests',
  'Запускаться с этим профилем и не спрашивать': 'Always start with this profile',
  'Звёздочка в адресной строке сохраняет страницу сюда.': 'The star in the address bar saves the page here.',
  'Изменить': 'Edit',
  'Изменить имя, значок и промпт': 'Edit name, icon and prompt',
  'Или скажите словами': 'Or say it in words',
  'Имя группы': 'Group name',
  'Имя группы, например «Чтение»': 'Group name, e.g. Reading',
  'Имя и фамилия': 'Full name',
  'Имя, контакты и адрес доставки для форм заказа.': 'Name, contacts and shipping address for checkout forms.',
  'Канал': 'Channel',
  'Карт пока нет': 'No cards yet',
  'Карточка показывает, кто это. Здесь — что ему можно. Основной профиль нельзя удалить и нельзя просить стирать логины при выходе.': 'The card is who it is. Here is what it may do. The main profile cannot be deleted.',
  'Карточка слева — то дело, которое настраиваете. Переключение действует на новые вкладки, уже открытые остаются в своих сессиях.': 'The card on the left is the profile you are editing. The switch applies to new tabs.',
  'Ключ сейфа привязан к этому Windows-профилю и не переживёт переустановку. Сохраните копию под отдельной парольной фразой, чтобы не потерять пароли.': 'The vault key is tied to this Windows profile and will not survive a reinstall. Save a copy under a passphrase.',
  'Кнопка «Перевести страницу» в тулбаре может работать на одном из двух локальных движков. Оба считают полностью на устройстве, ничего не уходит в сеть.': 'Translate page can use one of two local engines. Both run on this device.',
  'Кнопки-сценарии над полем ввода в AI-панели (Объяснить, Сделать саммари и ваши свои) — каждая отправляет свой промпт про текущую страницу.': 'Scenario buttons in the AI panel each send their own prompt about the current page.',
  'Когда': 'When',
  'Коннекторов пока нет — сейф работает только свой': 'No connectors yet — only the built-in vault',
  'Копировать логин': 'Copy username',
  'Копировать пароль': 'Copy password',
  'Копия под парольной фразой': 'Copy under a passphrase',
  'Корни, которым сказали «доверять»': 'Roots you chose to trust',
  'Куки и логины': 'Cookies and logins',
  'Логин / e-mail': 'Username / email',
  'Логин:Пароль (опционально)': 'Login:Password (optional)',
  'Масштаб': 'Zoom',
  'Месяц (MM)': 'Month',
  'Минцифры': 'MinTsifry',
  'Модель': 'Model',
  'Можно спрашивать каждый раз или всегда открывать один и тот же профиль': 'Ask every time, or always open the same profile',
  'Мои правила': 'My rules',
  'На каком сайте': 'On which site',
  'На этой машине': 'On this machine',
  'Набор DuckDuckGo': 'DuckDuckGo set',
  'Название': 'Name',
  'Название кнопки': 'Button name',
  'Найдено': 'Found',
  'Найти сайт: wildberries, ozon, github…': 'Find a site: amazon, github…',
  'Наш формат, не CSV — фразу спросим и при восстановлении': 'Our format, not CSV — we will ask the phrase on restore too',
  'Ничего не подключено': 'Nothing connected',
  'Новое дело: «Работа», «Личное»…': 'New profile: Work, Personal…',
  'Номер карты выдаётся только после подтверждения личности через Windows Hello, а CVC не сохраняется вовсе — ни зашифрованным, ни каким-либо ещё.': 'The card number is shown only after Windows Hello. CVC is never stored.',
  'Номер карты хранится зашифрованным; для показа запросим подтверждение Windows.': 'The card number is encrypted; showing it asks Windows to confirm.',
  'Облако предлагается там, где ответ сочиняют. Там, где модель выбирает из готового набора, сильная модель сделает то же самое — только за деньги и медленнее.': 'Cloud is for composing answers. For picking from a fixed set, a strong model does the same — slower and paid.',
  'Область / регион': 'Region',
  'Обновить счётчик': 'Refresh count',
  'Опишите фразой, что браузер должен делать сам — «ссылки с habr.com открывай в группе Чтение». Правило появится карточкой на подтверждение и заработает только после вашего «да».': 'Say what the browser should do. The rule appears as a confirmation card and runs only after you accept.',
  'Организация (необязательно)': 'Organization (optional)',
  'Откройте сайт, найдите на нём что-нибудь — шаблон соберётся по адресу результатов.': 'Open a site and search on it — the template is taken from the results URL.',
  'Открыть': 'Open',
  'Отменить': 'Cancel',
  'Отозвать доверие': 'Revoke trust',
  'Пароли современного Chrome зашифрованы и напрямую не переносятся. Выгрузите их в самом браузере: Настройки → Пароли → ⋮ → Экспорт паролей — и выберите полученный файл здесь.': 'Modern Chrome passwords cannot be copied directly. Export them in Chrome, then pick that file here.',
  'Пароль или PIN учётной записи': 'Account password or PIN',
  'Парольная фраза для импорта': 'Import passphrase',
  'Парольная фраза для экспорта': 'Export passphrase',
  'Перед тем как показать или скопировать сохранённый пароль': 'Before showing or copying a saved password',
  'По смыслу': 'By meaning',
  'По ходу работы': 'As you go',
  'Подключения к моделям': 'Model connections',
  'Подключить внешний менеджер': 'Connect an external manager',
  'Подтверждение': 'Confirmation',
  'Поиск по сайту или логину…': 'Search by site or username…',
  'Поиск смотрит по имени файла и по сайту, откуда он приехал.': 'Search looks at the file name and the site it came from.',
  'Поиск смотрит по названию закладки и по адресу — и всегда по всему сейфу, а не внутри выбранной папки.': 'Search looks at bookmark names and addresses across the whole vault.',
  'Полная индексация истории': 'Full history index',
  'Потрачено': 'Spent',
  'Правил пока нет': 'No rules yet',
  'Пример': 'Example',
  'Проверка утверждений страницы по источникам в интернете. Ключ хранится зашифрованным, не обычным текстом.': 'Checks page claims against sources. The key is stored encrypted.',
  'Промпт уходит модели вместе с текстом текущей страницы.': 'The prompt is sent with the current page text.',
  'Промпт — что отправить модели про текущую страницу': 'Prompt sent with the current page',
  'Распознать поиск на открытых сайтах': 'Detect search on open sites',
  'Ровно тот набор и в том порядке, что вы отметите ниже.': 'Exactly the set and order you pin below.',
  'Сайт не спросит снова': 'The site will not ask again',
  'Сайт, на котором вы сейчас': 'The site you are on',
  'Сайтов': 'Sites',
  'Сайты, где вы уже искали, и ваши бэнги — частые впереди. Список меняется сам.': 'Sites you already searched and your bangs, frequent first.',
  'Сайты, которым вы разрешили сертификаты удостоверяющего центра Минцифры — ответив «доверять» на вопрос браузера. Банки, у которых другого сертификата не бывает, работают и без этого списка.': 'Sites you allowed to use MinTsifry certificates. Banks that have no other cert work without this list.',
  'Свои': 'Custom',
  'Свой ключ провайдера. Платите вы напрямую ему — мы не посредник и своих ключей не держим. Ключ хранится зашифрованным и наружу из браузера не возвращается.': 'Your provider key. You pay them directly. The key stays encrypted and does not leave the browser.',
  'Свой поисковый сервер для web-grounding в AI-панели. Адрес и токен хранятся зашифрованными, не обычным текстом.': 'Your search server for grounding in the AI panel. Address and token stay encrypted.',
  'Сейф пока один на устройство': 'One vault per device for now',
  'Сеть': 'Network',
  'Скачанные файлы — в общей папке': 'Downloads go to a shared folder',
  'Скачать заново': 'Download again',
  'Список моделей': 'Model list',
  'Список свёрнут не для красоты: каждая строка тянет значок своего сайта, и раскрытый сейф рассылает список ваших аккаунтов по чужим серверам.': 'The list stays collapsed so opening Settings does not fetch a favicon for every saved account.',
  'Спрашивать': 'Ask',
  'Текст страницы для умного поиска появляется при обычном просмотре. Перенесённые из другого браузера адреса без повторного визита в поиск по смыслу не попадают — их добирает кнопка ниже.': 'Page text for semantic search appears as you browse. Imported addresses need the button below.',
  'Тогда': 'Then',
  'Токенов наружу': 'Tokens sent out',
  'Только закреплённые': 'Pinned only',
  'Убрать из закреплённых': 'Unpin',
  'Убрать из списка': 'Remove from list',
  'Удалить бэнг': 'Delete bang',
  'Удалить из истории': 'Remove from history',
  'Удалить правило': 'Delete rule',
  'Удалить профиль вместе с его логинами': 'Delete profile and its logins',
  'Улица, дом, квартира': 'Street, building, apt',
  'Файлы, которые вы скачаете, останутся здесь — вместе с адресом страницы, откуда они пришли.': 'Files you download stay here, with the page they came from.',
  'Фактчек — ключ Gemini': 'Fact-check · Gemini key',
  'Фразу разберёт локальная модель и покажет, что из неё поняла. Это только удобство: те же правила собираются формой выше, без модели.': 'The local model parses the phrase. The same rules can be built with the form above.',
  'Хранение': 'Storage',
  'Цель потерялась': 'Target is gone',
  'Что чем считается': 'What uses which model',
  'Чтобы Oblako брал пароли из того сейфа, которым вы уже пользуетесь.': 'Let Oblako use the vault you already have.',
  'Экран выбора профиля при каждом запуске': 'Profile picker at every launch',
  'в адресной строке': 'in the address bar',
  'в профиле, не в приложении': 'in the profile, not the app',
  'ключ в учётной записи Windows, не в облаке': 'key in the Windows account, not the cloud',
  'ключ, напр. og': 'key, e.g. og',
  'локальный, с секретом': 'local, with a secret',
  'название, напр. Overgear': 'name, e.g. Overgear',
  'разных доменов в сейфе': 'distinct domains in the vault',
  'ссылки с habr.com открывай в группе Чтение': 'open habr.com links in the Reading group',

  'Отслеживание': 'Tracking',
  'Поиск везде': 'Search all',
  'везде': 'all',
  'Искать по истории…': 'Search history…',
  'Искать по закладкам…': 'Search bookmarks…',
  'Искать по загрузкам…': 'Search downloads…',
  'Искать по товарам…': 'Search products…',
  'Искать по обращениям…': 'Search requests…',
  'Один вопрос по истории, закладкам и загрузкам — Enter': 'Ask across history, bookmarks and downloads — Enter',
  'Настроить AI': 'AI settings',
  'Ищем сразу по истории, закладкам и загрузкам — по Enter': 'Searching all libraries — press Enter',
  'Искать сразу по истории, закладкам и загрузкам': 'Search history, bookmarks and downloads',

  'страниц за сегодня пока нет': 'no pages today yet',
  'За сегодня': 'Today',
  'открытых страниц': 'pages opened',
  'разных доменов в списке': 'distinct domains',
  'Записей': 'Entries',
  'загружено в этот список': 'loaded in this list',
  'Поиск по смыслу': 'Semantic search',
  'Qwen переранжирует находки': 'Qwen reranks results',
  'Включён': 'On',
  'Выключен': 'Off',
  'Qwen переранжирует…': 'Qwen is ranking…',
  'Найти по смыслу': 'Search by meaning',
  'История пуста': 'History is empty',
  'Попробуйте другое слово — поиск смотрит и по заголовкам страниц, и по адресам.': 'Try another word — search looks at titles and addresses.',
  'Страницы, которые вы откроете, появятся здесь по дням — и их можно будет найти словом из текста.': 'Pages you open appear here by day, and you can find them by a word from the text.',
  'вы пока ничего не сохранили': 'nothing saved yet',
  'Всего': 'Total',
  'ссылок в сейфе': 'links in the vault',
  'Папок': 'Folders',
  'папок пока нет': 'no folders yet',
  'лежат в общей куче': 'in the unsorted pile',
  'За месяц': 'This month',
  'добавлено новых': 'added new',
  'В этой папке пусто': 'This folder is empty',
  'Разложить по папкам': 'Sort into folders',
  'Разбираю…': 'Sorting…',
  'вы пока ничего не скачивали': 'nothing downloaded yet',
  'Файлов': 'Files',
  'за всё время': 'all time',
  'Занимают': 'Size',
  'на диске': 'on disk',
  'скачано': 'downloaded',
  'Не получилось': 'Failed',
  'прервано или пропало': 'interrupted or missing',
  'на паузе': 'paused',
  'файла на месте нет': 'file is missing',
  'отменено': 'cancelled',
  'прервано': 'interrupted',
  'развернуть': 'expand',
  'Удалить из закладок': 'Remove bookmark',
  'Показать модели провайдера': 'Show provider models',
  'Windows спрашивает PIN': 'Windows asks for a PIN',
  'Windows не спрашивает': 'Windows does not ask',
  'Читаю сейф…': 'Reading the vault…',
  'Записей пока нет': 'No entries yet',
  'Значки сайтов загружены': 'Site icons loaded',
  'Значки сайтов не загружаются, пока список свёрнут': 'Site icons stay unloaded while the list is collapsed',
  'Скрыть пароль': 'Hide password',
  'Показать пароль': 'Show password',
  'Генератор паролей': 'Password generator',
  'Скрыть номер': 'Hide number',
  'Показать номер': 'Show number',
  'Сервер работает': 'Server is running',
  'Не подключено': 'Not connected',
  'Настроено': 'Set up',
  'Не настроено': 'Not set up',
  'Правила': 'Rules',
  'Профили': 'Profiles',
  'Разрешения': 'Permissions',
  'Автозаполнение': 'Autofill',
  'Курс ЦБ': 'CBR rates',
  'Крипта, ₽': 'Crypto, ₽',
};
