// Строки разделов со смешанным EN/RU: роли AI, пароли, профили, правила, агенты, трекинг.
export const REST: Record<string, string> = {
  'Взять из открытой вкладки': 'From the open tab',
  'Распознать поиск на открытых сайтах': 'Detect search on open sites',
  'Откройте сайт, найдите на нём что-нибудь — шаблон соберётся по адресу результатов.': 'Open a site, search on it — the template is built from the results URL.',
  'Распознать': 'Detect',
  'Среди открытых вкладок поиска не нашлось. Откройте нужный сайт, найдите на нём что-нибудь и нажмите «Распознать» ещё раз.': 'No search found in open tabs. Open the site, search on it and press Detect again.',
  'Скрыть': 'Hide',
  'Заполнить': 'Fill in',
  'Добавить свой': 'Add your own',
  'ключ, напр. og': 'key, e.g. og',
  'название, напр. Overgear': 'name, e.g. Overgear',
  'Удалить бэнг': 'Delete bang',
  'своих пока нет': 'none yet',
  'Набор DuckDuckGo': 'DuckDuckGo set',
  'в профиле, не в приложении': 'in the profile, not the app',
  'Не скачан': 'Not downloaded',
  'Пример': 'Example',
  'в адресной строке': 'in the address bar',
  'Свои и встроенные бэнги всё равно имеют приоритет над импортированными.': 'Your bangs and built-in ones still override imported ones.',
  'Несколько тысяч готовых бэнгов. Скачивается в ваш профиль, в приложение не входит.': 'A few thousand ready bangs. Downloads into your profile, not into the app.',
  'Загрузка…': 'Loading…',
  'Обновить': 'Refresh',
  'Не удалось импортировать': 'Could not import',
  'Импортировано {n}': 'Imported {n}',

  'Локальная модель работает на этом устройстве и ничего не отправляет. Облачные сервисы ниже подключаются по отдельности и только вашим ключом.': 'The local model runs on this device and sends nothing out. Cloud services below connect separately, with your key only.',
  'скачайте модель ниже — без неё не работают скиллы, перевод и поиск по смыслу': 'download a model below — skills, translation and semantic search need it',
  'загружена в память — отвечает сразу, ничего не отправляет наружу': 'loaded in memory — replies at once, sends nothing out',
  'готова — поднимется в память при первом запросе': 'ready — loads into memory on first use',
  'ни одна не установлена': 'none installed',
  'В памяти': 'In memory',
  'Готова': 'Ready',
  'Локально': 'Local',
  'Ключ есть': 'Key saved',
  'Выключен': 'Off',
  'Настроен': 'Set up',
  '{n} ГБ на диске': '{n} GB on disk',
  'Здесь': 'Here',
  'Облако предлагается там, где ответ сочиняют. Там, где модель выбирает из готового набора, сильная модель сделает то же самое — только за деньги и медленнее.': 'Cloud is for composing answers. For picking from a fixed set, a strong model does the same — slower and paid.',
  'Наружу уходит: {what}': 'Sent out: {what}',
  'Перевод страницы целиком': 'Full-page translation',
  'текст всей страницы, батчами': 'the whole page, in batches',
  'Работа со страницей': 'Page work',
  'выделенный фрагмент — перевод, пересказ, упрощение, объяснение; изменения страницы; карточки товаров': 'the selection — translate, recap, simplify, explain; page edits; product cards',
  'Чат': 'Chat',
  'ваши сообщения и вложенный контекст вкладки': 'your messages and the tab context',
  'Блокнот, Студия и граф': 'Notebook, Studio and graph',
  'текст источников, которые вы добавили сами': 'source text you added yourself',
  'Поиск и адресная строка': 'Search and address bar',
  'запрос и заголовки из истории, вкладок и настроек': 'the query and titles from history, tabs and settings',
  'Порядок и имена': 'Order and names',
  'заголовки и адреса вкладок, закладок и загрузок': 'titles and URLs of tabs, bookmarks and downloads',
  'Разбор форм': 'Form parsing',
  'названия полей формы — не то, что вы в них ввели': 'form field names — not what you typed',
  'Итоги дня': 'Day digest',
  'заголовки страниц, прочитанных за день': 'titles of pages read today',
  'Правила из фразы': 'Rules from a phrase',
  'фраза, которую вы написали сами': 'the phrase you typed',
  'Генератор виджетов': 'Widget generator',
  'Страницу целиком переводит движок перевода — Bergamot или локальная Qwen, выбор в настройках. Перевести отдельный фрагмент любой подключённой моделью можно в поповере над выделением и в AI-панели.': 'Full pages go through Bergamot or local Qwen, chosen in settings. A selection can use any connected model in the popover and AI panel.',
  'Считается, пока вы набираете, — ответ из облака придёт позже, чем нужен.': 'It runs while you type — a cloud reply would arrive too late.',
  'Модель выбирает из готового набора: облако сделает то же самое, но за деньги.': 'The model picks from a fixed set: cloud does the same, for money.',
  'Расход': 'Usage',
  'Обнулить счёт': 'Reset count',
  'Запросов': 'Requests',
  'счёт начнётся с первого ответа': 'starts with the first reply',
  'все — на этой машине': 'all on this machine',
  'наружу ушло {n}': '{n} sent out',
  'Токенов наружу': 'Tokens sent out',
  'облако ещё не отвечало': 'cloud has not replied yet',
  'на приём {n}': '{n} received',
  'Потрачено': 'Spent',
  'по данным провайдера': 'as reported by the provider',
  'провайдер не сообщает цену': 'the provider does not report a price',
  'На этой машине': 'On this machine',
  'не использовалась': 'not used',
  'запросов {n}': '{n} requests',
  'Рекомендуем': 'Recommended',
  'Помощнее': 'Stronger',
  '{size} ГБ загрузки · нужно {n} ГБ видеопамяти': '{size} GB download · {n} GB video memory needed',
  'Минимальный вариант для слабых видеокарт. Качество на наших функциях не измерялось — возможны осечки.': 'Smallest option for weak GPUs. Quality on our features was not measured — misses are possible.',
  'Быстрые ответы и самая точная работа с вкладками, поиском и правилами. Пересказ текста короче и суше.': 'Fast replies and the most accurate work with tabs, search and rules. Recaps are shorter and drier.',
  'Лучше пересказывает и связнее пишет. Отвечает медленнее и требует заметно больше видеопамяти.': 'Better recaps and more coherent writing. Slower, and needs more video memory.',
  'Для мощных видеокарт: самый связный текст ценой скорости и памяти.': 'For powerful GPUs: the most coherent text, at the cost of speed and memory.',
  '{n} ГБ': '{n} GB',
  'видеопамять: {n}': 'video memory: {n}',
  'Нет': 'No',
  'Скачать': 'Download',

  'записей в сейфе на этом устройстве · ключ привязан к учётной записи Windows': 'entries in the vault on this device · the key is tied to the Windows account',
  'Сейф зашифрован и никуда не отправляется. Автозаполнение в веб-формы появится отдельным шагом.': 'The vault is encrypted and never sent anywhere. Autofill into web forms comes as a later step.',
  'Перед тем как показать или скопировать сохранённый пароль': 'Before showing or copying a saved password',
  'Подтверждение': 'Confirmation',
  'Пароль или PIN учётной записи': 'Account password or PIN',
  'Спрашивает': 'Asks',
  'Не спрашивает': 'Does not ask',
  'Сайтов': 'Sites',
  'разных доменов в сейфе': 'distinct domains in the vault',
  'Хранение': 'Storage',
  'ключ в учётной записи Windows, не в облаке': 'key in the Windows account, not the cloud',
  'На устройстве': 'On this device',
  'Скоро': 'Soon',
  'Сохранённые пароли': 'Saved passwords',
  'Список свёрнут не для красоты: каждая строка тянет значок своего сайта, и раскрытый сейф рассылает список ваших аккаунтов по чужим серверам.': 'The list stays collapsed so opening Settings does not fetch a favicon for every saved account.',
  'Читаю сейф…': 'Reading the vault…',
  'Записей пока нет': 'No entries yet',
  '{n} запись': '{n} entry',
  '{n} записи': '{n} entries',
  '{n} записей': '{n} entries',
  'Значки сайтов загружены': 'Site icons are loaded',
  'Значки сайтов не загружаются, пока список свёрнут': 'Site icons stay unloaded while the list is collapsed',
  'Свернуть': 'Collapse',
  'Показать': 'Show',
  'Поиск по сайту или логину…': 'Search by site or login…',
  'Сбросить': 'Clear',
  'Перенести из другого браузера': 'Import from another browser',
  'Пароли современного Chrome зашифрованы и напрямую не переносятся. Выгрузите их в самом браузере: Настройки → Пароли → ⋮ → Экспорт паролей — и выберите полученный файл здесь.': 'Modern Chrome passwords cannot be copied directly. Export them in Chrome, then pick that file here.',
  'Выбрать файл': 'Choose file',
  'Зашифрованная копия сейфа': 'Encrypted vault copy',
  'Ключ сейфа привязан к этому Windows-профилю и не переживёт переустановку. Сохраните копию под отдельной парольной фразой, чтобы не потерять пароли.': 'The vault key is tied to this Windows profile and will not survive a reinstall. Save a copy under a separate passphrase.',
  'Копия под парольной фразой': 'Copy under a passphrase',
  'Наш формат, не CSV — фразу спросим и при восстановлении': 'Our format, not CSV — we will ask for the phrase on restore',
  'Подключить внешний менеджер': 'Connect an external manager',
  'Чтобы Oblako брал пароли из того сейфа, которым вы уже пользуетесь.': 'So Oblako can use the vault you already have.',
  'Коннекторов пока нет — сейф работает только свой': 'No connectors yet — only the built-in vault works',
  'Windows asks for a PIN': 'Windows asks for a PIN',

  'Адреса и банковские карты для быстрого заполнения форм. Данные зашифрованы на этом устройстве; CVC/CVV карт не сохраняется. Подстановка в формы появится следующим шагом.': 'Addresses and bank cards for filling forms. Data is encrypted on this device; card CVC/CVV is not stored. Filling into forms comes next.',
  'Адреса': 'Addresses',
  'Имя, контакты и адрес доставки для форм заказа.': 'Name, contacts and delivery address for checkout forms.',
  'Банковские карты': 'Bank cards',
  'Номер карты хранится зашифрованным; для показа запросим подтверждение Windows.': 'The card number is stored encrypted; showing it asks Windows to confirm.',
  'Карт пока нет': 'No cards yet',
  'Разбираю…': 'Parsing…',
  'Разобрать': 'Parse',

  'Пусто': 'Empty',
  'сайт с сохранённым решением': 'site with a saved decision',
  'сайтов с сохранённым решением': 'sites with a saved decision',
  'Что сайты могут запрашивать у браузера. Решение запоминается, когда вы отвечаете на вопрос с галочкой «запомнить», — здесь его можно посмотреть и изменить.': 'What sites can ask the browser. A decision is saved when you answer with “remember” checked — review and change it here.',
  'Есть сохранённое решение': 'A decision is saved',
  'Сайт не спросит снова': 'The site will not ask again',
  'Минцифры': 'MinTsifry',
  'Корни, которым сказали «доверять»': 'Roots you chose to trust',
  'Пока ни одно решение не сохранено. Сайты будут спрашивать при первой попытке.': 'No decisions saved yet. Sites will ask on first attempt.',
  '1 решение': '1 decision',
  '{n} решения': '{n} decisions',
  '{n} решений': '{n} decisions',
  'Сбросить всё': 'Reset all',
  'Забыть все решения по этому сайту': 'Forget every decision for this site',
  'Открытие приложений': 'Open apps',
  'Камера': 'Camera',
  'Микрофон': 'Microphone',
  'Камера и микрофон': 'Camera and microphone',
  'Местоположение': 'Location',
  'Уведомления': 'Notifications',
  'Полный экран': 'Fullscreen',
  'Чтение буфера обмена': 'Read clipboard',
  'Запись в буфер обмена': 'Write clipboard',
  'Отозвать доверие': 'Revoke trust',
  'Сайты, которым вы разрешили сертификаты удостоверяющего центра Минцифры — ответив «доверять» на вопрос браузера. Банки, у которых другого сертификата не бывает, работают и без этого списка.': 'Sites you allowed Ministry of Digital certificates — by answering “trust” in the prompt. Banks that have no other certificate still work without this list.',

  'активен сейчас · переключение действует на новые вкладки': 'active now · switching applies to new tabs',
  'Куки и логины': 'Cookies and logins',
  'Два аккаунта одного сайта рядом': 'Two accounts for the same site',
  'Свои': 'Own',
  'Сеть': 'Network',
  'Своя': 'Own',
  'История и закладки': 'History and bookmarks',
  'Скачанные файлы — в общей папке': 'Downloads go to a shared folder',
  'Сейф пока один на устройство': 'One vault per device for now',
  'Общие': 'Shared',
  'Ваши профили': 'Your profiles',
  'Карточка слева — то дело, которое настраиваете. Переключение действует на новые вкладки, уже открытые остаются в своих сессиях.': 'The card on the left is the profile you are editing. The switch applies to new tabs; open ones stay in their sessions.',
  'Основной': 'Main',
  'Профиль': 'Profile',
  'Активен': 'Active',
  'Открывается при запуске': 'Opens at launch',
  'Стирает логины при выходе': 'Clears logins on quit',
  'Мобильные версии': 'Mobile sites',
  'Свой облик': 'Custom look',
  'Свои куки и логины': 'Own cookies and logins',
  'Выход': 'Network',
  'Сайтам': 'Sites see',
  'Облик': 'Look',
  'Свой': 'Custom',
  'Включена': 'On',
  'Выключена': 'Off',
  'Компьютер': 'Computer',
  'Обычные версии сайтов': 'Desktop site versions',
  'Телефон': 'Phone',
  'Мобильные версии сайтов — не анонимность, а удобство': 'Mobile site versions — convenience, not anonymity',
  'Как в приложении': 'Follow app',
  'Профиль не просит ничего особенного': 'The profile asks for nothing special',
  'Сайты отвечают по-русски, где умеют': 'Sites reply in Russian when they can',
  'Сайты отвечают по-английски, где умеют': 'Sites reply in English when they can',
  'Тема профиля не задана': 'No profile theme set',
  'Всегда светлая, что бы ни стояло в приложении': 'Always light, whatever the app uses',
  'Всегда тёмная, что бы ни стояло в приложении': 'Always dark, whatever the app uses',
  'Следует общему переключателю VPN': 'Follows the app VPN switch',
  'Только через VPN': 'VPN only',
  'Туннель упал — профиль ждёт, а не выходит напрямую': 'If the tunnel drops, the profile waits instead of going direct',
  'Без VPN': 'No VPN',
  'Прямой выход, даже когда VPN включён в приложении': 'Direct even when the app VPN is on',
  'Оставлять': 'Keep',
  'Профиль помнит, где вы вошли': 'The profile remembers where you signed in',
  'Стирать': 'Erase',
  'При закрытии браузера логины этого профиля пропадут': 'Logins of this profile vanish when the browser quits',
  'При запуске браузера': 'At launch',
  'Можно спрашивать каждый раз или всегда открывать один и тот же профиль': 'Ask every time, or always open the same profile',
  'Спрашивать': 'Ask',
  'Экран выбора профиля при каждом запуске': 'Profile picker on every launch',
  'Всегда «{name}»': 'Always “{name}”',
  'Запускаться с этим профилем и не спрашивать': 'Launch this profile and do not ask',
  'Удалить профиль вместе с его логинами': 'Delete the profile and its logins',
  'Новое дело: «Работа», «Личное»…': 'New profile: Work, Personal…',
  'Карточка показывает, кто это. Здесь — что ему можно. Основной профиль нельзя удалить и нельзя просить стирать логины при выходе.': 'The card is who it is. Here is what it may do. The main profile cannot be deleted.',
  'Буква': 'Letter',
  'Эмодзи': 'Emoji',
  'Фото': 'Photo',
  'Готовлю…': 'Preparing…',
  'Настройки «{name}»': 'Settings for “{name}”',

  'Браузер сам делает мелкую работу: раскладывает вкладки по группам, закрепляет нужные, включает VPN на выбранных сайтах. Правило выполняется обычным кодом — модель для этого не нужна и не запускается.': 'The browser does small jobs itself: groups tabs, pins the ones you need, turns VPN on for chosen sites. A rule is ordinary code — the model is not started.',
  'Новое правило': 'New rule',
  'Когда': 'When',
  'На каком сайте': 'On which site',
  'Тогда': 'Then',
  'Открываю страницу на сайте': 'I open a page on the site',
  'Сработает на самом сайте и его поддоменах': 'Runs on the site and its subdomains',
  'Перехожу по ссылке с сайта': 'I follow a link from the site',
  'Сработает на странице, куда увела ссылка с этого сайта': 'Runs on the page that link opened',
  'Класть вкладку в группу': 'Put the tab in a group',
  'Закреплять вкладку': 'Pin the tab',
  'Не блокировать рекламу на этом сайте': 'Do not block ads on this site',
  'Включать VPN и перезагружать страницу': 'Turn VPN on and reload',
  'Домен покрывает и поддомены: habr.com — это и m.habr.com.': 'A domain covers subdomains: habr.com includes m.habr.com.',
  'Не похоже на адрес сайта': 'That does not look like a site address',
  'Или скажите словами': 'Or say it in words',
  'Фразу разберёт локальная модель и покажет, что из неё поняла. Это только удобство: те же правила собираются формой выше, без модели.': 'The local model parses the phrase and shows what it understood. The same rules can be built with the form above, without a model.',
  'ссылки с habr.com открывай в группе Чтение': 'open habr.com links in the Reading group',
  'Мои правила': 'My rules',
  '{n} из {max}. Выключенное правило остаётся в списке, но не выполняется.': '{n} of {max}. A disabled rule stays in the list but does not run.',
  'Создать правило': 'Create rule',
  'Отмена': 'Cancel',
  'Удалить правило': 'Delete rule',
  'Правил пока нет': 'No rules yet',
  'когда открываю страницу на {d}': 'when I open a page on {d}',
  'когда перехожу по ссылке с {d}': 'when I follow a link from {d}',
  'класть вкладку в группу «{name}»': 'put the tab in the “{name}” group',
  'закреплять вкладку': 'pin the tab',
  'переводить страницу': 'translate the page',
  'открывать с масштабом {n}%': 'open at {n}% zoom',
  'открывать без звука': 'open muted',
  'не блокировать рекламу на этом сайте': 'do not block ads on this site',
  'включать VPN и перезагружать страницу': 'turn VPN on and reload',
  'Имя группы': 'Group name',
  'Имя группы, например «Чтение»': 'Group name, e.g. Reading',
  'Имя группы можно поправить — его вы будете видеть в списке вкладок.': 'You can edit the group name — it is what you will see in the tab list.',
  'Масштаб': 'Zoom',

  'программа подключена': 'program connected',
  'программ подключено': 'programs connected',
  'сервер выключен': 'server is off',
  'Браузер наружу не отдаётся': 'The browser is not shared',
  'Включить можно в настройках, раздел «AI» — там же лежит команда подключения.': 'Turn it on in Settings → AI — the connect command is there too.',
  'Подключено': 'Connected',
  'спрашивали разрешение лично': 'asked you in person',
  'Обращений': 'Calls',
  'за время работы браузера': 'while the browser was open',
  'Отказов': 'Denied',
  'не разрешили или не смогли': 'refused or failed',
  'Канал': 'Channel',
  'Без порта': 'No port',
  'локальный, с секретом': 'local, with a secret',
  'Программы': 'Programs',
  'Все обращения': 'All calls',
  'Обращения этой программы': 'Calls from this program',
  'пока пусто': 'empty so far',
  'отказ': 'denied',
  'Можно': 'Allow',
  'Никогда': 'Never',
  'Разрешённые сайты': 'Allowed sites',
  'программа не видит ничего, кроме перечисленного': 'the program sees only what is listed',
  'пусто — ограничений нет, программе видны любые сайты': 'empty — no limit, any site is visible',
  'Применяю…': 'Applying…',
  'Применить': 'Apply',
  'Стучались, но не подключены': 'Knocked, not connected',
  'карточка ждала в окне браузера — можно подключить и отсюда': 'a card waited in the browser — you can connect from here too',
  'назвалась так сама · проверить это мы не можем': 'it named itself · we cannot verify that',
  'профиль «{name}» · назвалась так сама, проверить это мы не можем': 'profile “{name}” · it named itself, we cannot verify that',

  'вы пока ничего не отслеживаете': 'you are not tracking anything yet',
  'подешевело с тех пор, как вы добавили · {n} товар': 'cheaper since you added it · {n} product',
  'подешевело с тех пор, как вы добавили · {n} товара': 'cheaper since you added it · {n} products',
  'подешевело с тех пор, как вы добавили · {n} товаров': 'cheaper since you added it · {n} products',
  'подорожало с тех пор, как вы добавили · {n} товар': 'more expensive since you added it · {n} product',
  'подорожало с тех пор, как вы добавили · {n} товара': 'more expensive since you added it · {n} products',
  'подорожало с тех пор, как вы добавили · {n} товаров': 'more expensive since you added it · {n} products',
  'Товаров': 'Products',
  'под наблюдением': 'watched',
  'Изменилось': 'Changed',
  'по всем наблюдениям': 'across all watches',
  'Проверка': 'Check',
  'пока браузер открыт': 'while the browser is open',
  'ещё не проверялось': 'not checked yet',
  'проверено только что': 'just now',
  'проверено {n} мин назад': '{n} min ago',
  'проверено {n} ч назад': '{n} h ago',
  'проверено {n} дн назад': '{n} d ago',
  'когда цена упала': 'when the price dropped',
  'Включены': 'On',
  'Молча': 'Silent',
  'Браузер сам перепроверяет цены, пока открыт. Часть магазинов не отдаёт цену роботу — это видно по дате проверки.': 'The browser rechecks prices while it is open. Some shops hide the price from bots — that shows in the check date.',
  'Уведомления включены': 'Notifications on',
  'Уведомления выключены': 'Notifications off',
  'Уведомлять': 'Notify',
  'Проверить сейчас': 'Check now',
  'Пока ничего не отслеживается': 'Nothing is tracked yet',
  'Откройте карточку товара и нажмите значок в адресной строке — браузер начнёт следить за ценой.': 'Open a product page and press the icon in the address bar — the browser will watch the price.',
  'минимум за всё время наблюдений': 'lowest since tracking started',
  'максимум за всё время наблюдений': 'highest since tracking started',
  'нет в наличии': 'out of stock',
  'осталось мало': 'low stock',
  'Не отслеживать': 'Stop tracking',
  'Открыть страницу товара': 'Open product page',
  'Вынуть из группы — это другой товар': 'Ungroup — this is a different product',
  'Ответили {ok} из {total}': '{ok} of {total} replied',
  'Источники:': 'Sources:',
  'Нет модели': 'No model',
  'смотрю, что установлено': 'checking what is installed',

  'Готовый набор': 'Ready-made set',
  'Тема профиля': 'Profile theme',
  'Так понял браузер': 'That is what the browser understood',
  'Видеокарта не обнаружена — модель считается на процессоре: ответы в разы медленнее, а в оперативной памяти она занимает столько же, сколько заняла бы в видеопамяти.': 'No GPU found — the model runs on the CPU: replies are much slower, and it uses as much RAM as it would video memory.',
  'Как выглядит': 'Look',
  'Добавить адрес': 'Add address',
  'Добавить карту': 'Add card',
  'Когда загружать модель': 'When to load the model',
};
