// Оставшийся английский к публикации: поповеры, псевдовкладки, приложения, граф, блокнот, виджеты.
export const LAUNCH: Record<string, string> = {
  'История посещений': 'Visit history',
  'Закладки': 'Bookmarks',
  'Загрузки': 'Downloads',
  'Загрузка…': 'Loading…',
  'Вкладка': 'Tab',

  'Здесь работает правило': 'A rule is active here',
  'Этот сайт': 'This site',
  'Изменилось с прошлого раза': 'Changed since last visit',
  'Подключаюсь': 'Connecting',
  'через VPN': 'via VPN',
  'ждёт VPN': 'waiting for VPN',
  'только через VPN': 'VPN only',
  'Выключить правило': 'Turn rule off',
  'Включить правило': 'Turn rule on',
  'Открыть настройки профилей': 'Open profile settings',
  'Забыть решение — сайт спросит снова': 'Forget — the site will ask again',

  'Скопировано со страниц': 'Copied from pages',
  'История копирования': 'Copy history',
  'История копирования выключена': 'Copy history is off',
  'Скопируйте что-нибудь на странице — попадёт сюда': 'Copy something on a page — it lands here',
  'Закреплённое': 'Pinned',
  'переживает перезапуск': 'survives restart',
  'Очистить незакреплённое': 'Clear unpinned',
  'Очистить всё': 'Clear all',
  'Собирается на этот сеанс': 'Kept for this session',
  'Выключена — собранное стёрто': 'Off — collected items were cleared',

  'Калькулятор': 'Calculator',
  'Конвертер': 'Converter',
  'Пояса': 'Time zones',
  'Пипетка': 'Eyedropper',
  'Котёнок': 'Kitten',
  'Счётчик': 'Counter',
  'Переводчик': 'Translator',
  'Фон': 'Wallpaper',
  'скрыто с экрана': 'hidden from the home screen',
  'Закрыть': 'Close',
  'Открыть': 'Open',
  'Удалить': 'Delete',
  'Скрыть с экрана': 'Hide from home',

  'Блокнот': 'Notebook',
  'источник выбран': 'source selected',
  'источников выбрано': 'sources selected',
  'Собрать материал': 'Gather sources',
  'Остановить': 'Stop',
  'Пишу страницу…': 'Writing the page…',
  'Генерирую по источникам…': 'Generating from sources…',
  'Добавить': 'Add',
  'извлекается…': 'extracting…',
  'не удалось извлечь': 'could not extract',
  'Материалы · {n} источн.': 'Sources · {n}',
  'Готовые': 'Ready',
  'Что искать': 'What to search',
  'Что добавить': 'What to add',
  'Подбираю запросы…': 'Picking queries…',
  'Ищу…': 'Searching…',
  'Кратко': 'Short',
  'Обычно': 'Normal',
  'Подробно': 'Long',
  'пусто': 'empty',
  'Страница': 'Page',
  'Студия': 'Studio',
  'Краткий пересказ по источникам': 'A short recap from the sources',
  'Ветвистая карта идей': 'A branching map of ideas',
  'Визуальная сводка': 'A visual recap',
  'Вопросы по мотивам': 'Questions from the material',
  'Статья по источникам, три стиля': 'An article from the sources, three styles',
  'Соберите материал — блокнот ответит по нему': 'Add sources — the notebook will answer from them',
  'Добавьте ссылки, документы с диска или вставьте текст. Чат будет отвечать только по ним, а «Студия» соберёт из них пересказ, карту, тест или документ.': 'Add links, files from disk or paste text. Chat answers only from those, and Studio builds a recap, map, quiz or document.',
  'Добавить ссылку': 'Add a link',
  'Выбрать документы': 'Choose files',
  'Вставить текст': 'Paste text',
  'Ничего не добавлено': 'Nothing added',
  'Добавить документы с диска': 'Add files from disk',
  'Добавить адрес или текст': 'Add a URL or text',

  'Новый граф': 'New graph',
  'Мой первый граф': 'My first graph',
  'Библиотека узлов': 'Node library',
  'Добавить узел': 'Add a node',
  'Откуда': 'Sources',
  'Обработка': 'Process',
  'Проверка': 'Check',
  'Артефакты': 'Artifacts',
  'Итог': 'Output',
  'Пометки': 'Notes',
  'Заметка': 'Note',
  'Файл': 'File',
  'Картинка': 'Image',
  'Черновик': 'Draft',
  'Сборка': 'Compose',
  'Промпт картинки': 'Image prompt',
  'Диалог': 'Chat',
  'Веб-чат': 'Web chat',
  'Веб-поиск': 'Web search',
  'Фактчек': 'Fact-check',
  'Саммари': 'Summary',
  'Майндкарта': 'Mind map',
  'Инфографика': 'Infographic',
  'Тест': 'Quiz',
  'Заметка на холсте': 'Canvas note',
  'Результат': 'Result',
  'текст': 'text',
  'ссылка': 'link',
  'вход': 'in',
  'ответ': 'reply',
  'блоки': 'blocks',
  'документ': 'document',
  'материал': 'material',
  'промпт': 'prompt',
  'последний ответ': 'last reply',
  'запрос': 'query',
  'находки': 'hits',
  'разбор': 'review',
  'аутлайн': 'outline',
  'спека': 'spec',
  'Не считался': 'Idle',
  'Устарел — входные данные изменились': 'Stale — inputs changed',
  'Ждёт очереди': 'Queued',
  'Считается': 'Running',
  'Ждёт вас — откройте чат и заберите ответ': 'Waiting — open the chat and take the reply',
  'Готово': 'Done',
  'Ошибка': 'Error',
  'не считался': 'idle',
  'устарел': 'stale',
  'в очереди': 'queued',
  'считается': 'running',
  'ждёт вас': 'waiting',
  'готово': 'done',
  'ошибка': 'error',
  'Загружает URL в фоне и достаёт читаемый текст': 'Loads a URL in the background and extracts readable text',
  'Произвольный текст, который вы вводите сами': 'Free text you type yourself',
  'Документ с диска: Word, PDF, текст, таблица CSV': 'A file from disk: Word, PDF, text, CSV',
  'Изображение с диска: реф или готовый результат генерации': 'An image from disk: a ref or a generated result',
  'Выполняет вашу инструкцию над тем, что пришло на вход': 'Runs your instruction on whatever arrived',
  'Текст, который вы правите руками посреди цепочки': 'Text you edit by hand in the middle of the chain',
  'Собирает готовый документ из входов по вашему шаблону, без модели': 'Builds a document from inputs by your template, no model',

  'Фактчек — ключ Gemini': 'Fact-check — Gemini key',
  'Проверка утверждений страницы по источникам в интернете. Ключ хранится зашифрованным, не обычным текстом.': 'Checks claims on the page against web sources. The key is stored encrypted, not as plain text.',
  'Не подключено': 'Not connected',
  'Ключ Gemini сохранён — кнопка фактчека доступна в AI-панели.': 'Gemini key saved — fact-check is available in the AI panel.',
  'Добавьте ключ, чтобы включить фактчек в AI-панели.': 'Add a key to turn on fact-check in the AI panel.',
  'Введите ключ': 'Enter the key',
  'Не удалось сохранить ключ': 'Could not save the key',
  'Сохранение…': 'Saving…',
  'Сохранить': 'Save',
  'SearXNG — веб-поиск для AI': 'SearXNG — web search for AI',
  'Свой поисковый сервер для web-grounding в AI-панели. Адрес и токен хранятся зашифрованными, не обычным текстом.': 'Your search server for grounding in the AI panel. Address and token are stored encrypted.',
  'Настроено': 'Set up',
  'Не настроено': 'Not set up',
  'Добавьте адрес сервера, чтобы включить веб-поиск в AI-панели.': 'Add a server address to turn on web search in the AI panel.',
  'Введите адрес сервера': 'Enter the server address',
  'Не удалось сохранить конфиг': 'Could not save the config',
  'Движок перевода страниц': 'Page translation engine',
  'Кнопка «Перевести страницу» в тулбаре может работать на одном из двух локальных движков. Оба считают полностью на устройстве, ничего не уходит в сеть.': 'Translate page in the toolbar can use one of two local engines. Both run on this device; nothing leaves the network.',
  'AI-перевод (медленно, выше качество)': 'AI translation (slower, higher quality)',
  'Qwen — универсальная модель, переводит любой язык, медленнее на CPU/GPU.': 'Qwen — a general model, any language, slower on CPU/GPU.',
  'Bergamot (быстрее, легче)': 'Bergamot (faster, lighter)',
  'готов': 'ready',
  'нет модели': 'no model',
  'Проверяю модель перевода…': 'Checking the translation model…',
  'Модель перевода не загружена — см. README (Bergamot).': 'Translation model is not loaded — see README (Bergamot).',
  'Специализированная модель для CPU — en/ru и ещё несколько языков.': 'A CPU model for en/ru and a few more languages.',
  'недоступен': 'unavailable',
  'Индексация истории для поиска': 'History indexing for search',
  'Текст страницы для умного поиска появляется при обычном просмотре. Перенесённые из другого браузера адреса без повторного визита в поиск по смыслу не попадают — их добирает кнопка ниже.': 'Page text for semantic search appears as you browse. Imported addresses need the button below, or a revisit.',
  'Обновить счётчик': 'Refresh the count',
  'Полный текст: считаю…': 'Full text: counting…',
  'Полная индексация истории': 'Full history indexing',
  'Для страниц, которые вы больше не откроете (например перенесённых из другого браузера). Тихо переоткрывает их в фоне и забирает текст. На большой истории занимает время, остановить можно в любой момент.': 'For pages you will not open again (for example imported ones). Reopens them quietly in the background and takes the text. On a large history this takes time; you can stop it.',
  'смотрю, что установлено': 'checking what is installed',

  'Новолуние': 'New moon',
  'Растущий серп': 'Waxing crescent',
  'Первая четверть': 'First quarter',
  'Растущая луна': 'Waxing gibbous',
  'Полнолуние': 'Full moon',
  'Убывающая луна': 'Waning gibbous',
  'Последняя четверть': 'Last quarter',
  'Убывающий серп': 'Waning crescent',
  'Освещена на {n}% · {day}-й день': '{n}% lit · day {day}',
  'заблокировано за сеанс': 'blocked this session',
  'тема за день': 'topic today',
  'темы за день': 'topics today',
  'тем за день': 'topics today',
  'Читаю историю за сегодня…': 'Reading today’s history…',
  'Сегодня ещё нечего обобщать': 'Nothing to recap yet today',
  'Соберу итог дня по вашей истории — локально, без сети': 'I’ll recap the day from your history — locally, offline',
  'Собираю…': 'Gathering…',
  'Собрать': 'Recap',
  'осталось {n}': '{n} left',
  'всё сделано': 'all done',
  'Вернуть в дела': 'Undo',
  'Сделано': 'Done',
  'Играть': 'Play',
  'Следующий': 'Next',
  'Предыдущий': 'Previous',
  'Подхватит любой сервис — виджет читает то, что играет во вкладке.': 'Any service — the widget reads what the tab is playing.',
  'Не удалось узнать': 'Could not load',
  'Ближайший праздник': 'Next holiday',
  'Доброй ночи': 'Good night',
  'Доброе утро': 'Good morning',
  'Добрый день': 'Good afternoon',
  'Добрый вечер': 'Good evening',
  'Градиент': 'Gradient',
  'Фото дня': 'Photo of the day',
  'Цвет': 'Color',
  'Стрелки': 'Hands',
  'Цифры': 'Digits',
  'Адблок': 'Ad block',
  'Ничего не играет': 'Nothing playing',
  'Музыка': 'Music',
  'день': 'day',
  'дня': 'days',
  'дней': 'days',

  'OpenAI-совместимый': 'OpenAI-compatible',
  'OpenAI, OpenRouter, DeepSeek, Groq, Ollama, LM Studio и любой свой адрес.': 'OpenAI, OpenRouter, DeepSeek, Groq, Ollama, LM Studio, or your own URL.',
  'Своя форма запроса: структуру ответа даёт инструмент.': 'Its own request shape: the tool supplies the response schema.',
  'Своя форма запроса и нативная схема ответа.': 'Its own request shape and native response schema.',
  'Ничего не подключено': 'Nothing connected',
  'Браузер работает на модели этой машины. Подключение нужно там, где ответ сочиняют: чат, работа со страницей, блокнот.': 'The browser runs on this machine’s model. A connection is for places that write: chat, page work, notebook.',
  'Нашли {label} на этой машине': 'Found {label} on this machine',
  '{n} модель — ответы не уходят с компьютера.': '{n} model — replies stay on this computer.',
  '{n} модели — ответы не уходят с компьютера.': '{n} models — replies stay on this computer.',
  '{n} моделей — ответы не уходят с компьютера.': '{n} models — replies stay on this computer.',
  'Подключить': 'Connect',
  'Новое подключение': 'New connection',
  'ключ не нужен': 'no key needed',
  'ключ провайдера': 'provider key',
  'Проверяю…': 'Checking…',
  'Проверить и сохранить': 'Test and save',
  'Адрес обязан быть https — по открытому http ключ уходит читаемым. Исключение — localhost.': 'The URL must be https — on plain http the key travels in the clear. Exception: localhost.',
  'Одновременно': 'At once',
  'Израсходовано': 'Used',
  'до {n} запросов': 'up to {n} requests',
  '{n} токенов': '{n} tokens',
  'Отвечает': 'Responding',
  'Не отвечает': 'No response',
  'Считается здесь': 'Runs here',
  'Нужен ключ': 'Key needed',
  'Полный текст: {n} из {m} страниц': 'Full text: {n} of {m} pages',
  'Полный текст: {n} из {m}. Остальные {k} — вход и служебные, в поиск по смыслу не идут.': 'Full text: {n} of {m}. The other {k} are login and utility pages, skipped by meaning search.',
  'Полный текст: {n} из {m}. Ещё {k} без текста — умный поиск их не видит, пока не откроете снова или не запустите полную индексацию.': 'Full text: {n} of {m}. {k} still have no text — meaning search cannot see them until you reopen them or run a full index.',
  'История пуста — умный поиск появится после просмотра страниц.': 'History is empty — meaning search appears after you visit pages.',
  'Проиндексировать полный текст': 'Index full text',
  'Обработано {n} из {m}…': 'Processed {n} of {m}…',
  'Остановлено: {n} из {m}': 'Stopped: {n} of {m}',
  'Готово: {n} из {m}': 'Done: {n} of {m}',
  'Идут настоящие сетевые запросы к этим сайтам: часть страниц может показать капчу, разлогинить или уже не существовать — такие просто пропускаются.': 'These are real network requests: some pages may show a captcha, log you out, or no longer exist — those are skipped.',
  'по данным провайдера': 'as reported by the provider',
  'Запущена, но ни одной модели не скачано. Скачайте любую — например, командой ollama pull qwen3.': 'Running, but no models are downloaded. Pull any one — for example, ollama pull qwen3.',
  'Запущена, но ни одной модели не загружено. Загрузите модель в самом приложении.': 'Running, but no model is loaded. Load a model in the app itself.',

  'работает': 'on',
  'выключено': 'off',
  'разрешено': 'allowed',
  'запрещено': 'blocked',
  'Внутренняя страница Oblako': 'Oblako internal page',
  'Шифруется': 'Encrypted',
  'Не шифруется — данные идут открытым текстом': 'Not encrypted — data travels in the clear',
  'Страница браузера': 'Browser page',
  'туннель поднят': 'tunnel is up',
  'трафик идёт напрямую': 'traffic goes direct',
  'этот сайт в исключениях': 'this site is excepted',
  'срезано за сеанс': 'cut this session',
  'Не режем': 'Not cutting',
  'сертификат в порядке': 'certificate is fine',
  'данные идут открытым текстом': 'data travels in the clear',
  'Соединение': 'Connection',
  'Открыто': 'Open',
  'сайт ничего не просил': 'the site has not asked',
  'сменить': 'switch',
  'Страница изменилась': 'The page changed',
  'Камера': 'Camera',
  'Микрофон': 'Microphone',
  'Камера и микрофон': 'Camera and microphone',
  'Открытие приложений': 'Opening apps',
  'Местоположение': 'Location',
  'Уведомления': 'Notifications',
  'Полный экран': 'Fullscreen',
  'Чтение буфера обмена': 'Clipboard read',
  'Запись в буфер обмена': 'Clipboard write',
  'Выключен': 'Off',

  'последнее': 'latest',
  'только что': 'just now',
  '{n} мин': '{n} min',
  '{n} ч': '{n} h',
  'без адреса': 'no address',
  'Скопировать снова': 'Copy again',
  'Свернуть': 'Collapse',
  'Показать целиком': 'Show all',
  'Скопировать адрес': 'Copy address',
  'Открепить': 'Unpin',
  'Закрепить — переживёт перезапуск': 'Pin — survives restart',
  'Открыть страницу и подсветить': 'Open the page and highlight',
  'Скопировать': 'Copy',
  'Убрать из списка': 'Remove from list',

  'За последний час': 'Last hour',
  'За сегодня': 'Today',
  'За неделю': 'This week',
  'За всё время': 'All time',
  'страниц за сегодня пока нет': 'no pages yet today',
  '{n} страница за сегодня': '{n} page today',
  '{n} страницы за сегодня': '{n} pages today',
  '{n} страниц за сегодня': '{n} pages today',
  '{n} находок': '{n} hits',
  '{n} страниц': '{n} pages',
  'открытых страниц': 'pages opened',
  'Сайтов': 'Sites',
  'разных доменов в списке': 'distinct domains in the list',
  'Записей': 'Entries',
  'загружено в этот список': 'loaded into this list',
  'Поиск по смыслу': 'Meaning search',
  'Qwen переранжирует находки': 'Qwen re-ranks the hits',
  'Включён': 'On',
  'Qwen переранжирует…': 'Qwen is re-ranking…',
  'Не удалось очистить историю. Попробуйте ещё раз.': 'Could not clear history. Try again.',
  'Показан быстрый результат — AI не ответил, порядок по сходству, не по смыслу.': 'Showing a fast result — AI did not answer; order is by similarity, not meaning.',
  'Ничего не нашлось': 'Nothing found',
  'История пуста': 'History is empty',
  'Попробуйте другое слово — поиск смотрит и по заголовкам страниц, и по адресам.': 'Try another word — search looks at page titles and addresses.',
  'Страницы, которые вы откроете, появятся здесь по дням — и их можно будет найти словом из текста.': 'Pages you open appear here by day — and you can find them by a word from the text.',
  'По смыслу': 'By meaning',
  'когда': 'when',
  'Удалить из истории': 'Remove from history',

  'Уже в работе': 'Already running',
  'Посчитать этот узел и всё, что от него зависит': 'Run this node and everything that depends on it',
  'Дублировать узел (Ctrl+D)': 'Duplicate node (Ctrl+D)',
  'Раскрыть на весь экран': 'Open fullscreen',
  'Удалить узел': 'Delete node',
  'Название узла': 'Node name',
  'Другой файл': 'Another file',
  'Выбрать файл': 'Choose a file',
  'Другая картинка': 'Another image',
  'Выбрать картинку': 'Choose an image',
  'Подпись (необязательно)': 'Caption (optional)',
  'Текст, который пойдёт дальше по графу': 'Text that continues through the graph',
  'Подставить текст питающих узлов': 'Insert text from feeding nodes',
  'Питающие узлы ещё ничего не выдали': 'Feeding nodes have not produced anything yet',
  'Выйти из графов — к новой вкладке': 'Leave graphs — back to a new tab',
  'Новый воркспейс': 'New workspace',
  'Переименовать': 'Rename',
  'Удалить воркспейс': 'Delete workspace',
  'Свернуть библиотеку': 'Collapse library',

  'Тема сбора': 'Topic',
  'Сначала модель предложит поисковые запросы. В сеть ничего не уйдёт, пока вы их не подтвердите.': 'The model will suggest search queries first. Nothing goes to the network until you confirm them.',
  'Запросы · правьте свободно': 'Queries · edit freely',
  'Убрать запрос': 'Remove query',
  '+ Свой запрос': '+ Your query',
  'Запросы уйдут на ваш SearXNG — ровно те, что здесь написаны.': 'Queries go to your SearXNG — exactly as written here.',
  'Ничего не нашлось. Попробуйте другие запросы.': 'Nothing found. Try other queries.',
  'Найдено · отметьте нужное': 'Found · pick what you need',
  'Отмена': 'Cancel',
  'Подобрать запросы': 'Suggest queries',
  'Искать': 'Search',
  'Добавить ({n})': 'Add ({n})',
  'Объём страницы': 'Page length',
  '~4 тыс. знаков · полминуты': '~4k characters · half a minute',
  '~8 тыс. знаков · минута-полторы': '~8k characters · a minute or so',
  'до 15 тыс. знаков · две-три минуты': 'up to 15k characters · two or three minutes',
  'Сменить блокнот · двойной клик — переименовать': 'Switch notebook · double-click to rename',
  '{n} источн.': '{n} sources',
  'Удалить блокнот': 'Delete notebook',
  '{n} знаков': '{n} characters',
  'Вставьте текст…': 'Paste text…',
  'Вставьте адрес сайта или текст…': 'Paste a site URL or text…',
  'Открыть документ': 'Open document',
  'Открыть в новой вкладке': 'Open in a new tab',
  'Повторить': 'Retry',
  'Открыть без пересборки': 'Open without rebuilding',
};
